<a href="https://colab.research.google.com/github/Stanislaff-666/python_practice/blob/main/Numpy_%D0%9E%D0%B4%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a=np.arange(1,10.5,0.5)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [ ]:
import numpy as np
a=np.linspace(-5,5,10)
print(a)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [ ]:
import numpy as np
a=np.arange(10,0.5,-1)
print(a)

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [ ]:
import numpy as np
a=int(input('введите число'))
arr=np.random.rand(a)
print(arr)

введите число10
[0.09178413 0.34518624 0.66275252 0.44171349 0.55148779 0.70371249
 0.58940123 0.04993276 0.56179184 0.76635847]


На вход подаются 2 числа a и b в виде строки чисел через пробел. Создайте массив NumPy, содержащий числа от a до b включительно, кратные 3, выведите его на экран,

In [ ]:
import numpy as np
a, b = map(int, input().split())
arr = np.arange(a, b + 1, 1)
res = []
for i in arr:
  if i % 3 == 0:
    res.append(i)
print(np.array(res))

-5 15
[-3  0  3  6  9 12 15]
[-3, 0, 3, 6, 9, 12, 15]


На вход подается целое число n. Cоздайте массив из n случайных действительных чисел в интервале от 0 до 1 не включительно.

Важно: перед генерацией чисел используйте строчку np.random.seed(32).

In [ ]:
import numpy as np
a=int(input())
np.random.seed(32)
arr=np.random.rand(a)
print(arr)


10
[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696  0.81620514
 0.10108656 0.92848807 0.60910917 0.59655344]


На вход подается целое число n>=1. Создайте массив, содержащий n первых простых чисел. Выведите его на экран.

In [ ]:
import numpy as np
from sympy import prime
a=int(input())
res = []
nth_prime = prime(range(1,a))
res.append(a)
print(res)


3


ValueError: ignored

In [ ]:
# import sympy
from sympy import prime
n = 5
# Use prime() method
nth_prime = prime(n)
print("The {}th prime is {}".format(n, nth_prime))

The 5th prime is 11


На вход подается 2 действительных числа а>0, b>=0.001. Создайте массив, содержащий числа от -a до числа c <= a, такого что a - c <= b, с шагом b. Числа округляйте до двух знаков после запятой, используя np.round(). Выведите массив на экран.

In [ ]:
a,b=input().split()
x=float(a)
y=float(b)
arr=np.round(np.arange (-x, x + y/10, y),1)
print(arr)

10 .3
[-10.   -9.7  -9.4  -9.1  -8.8  -8.5  -8.2  -7.9  -7.6  -7.3  -7.   -6.7
  -6.4  -6.1  -5.8  -5.5  -5.2  -4.9  -4.6  -4.3  -4.   -3.7  -3.4  -3.1
  -2.8  -2.5  -2.2  -1.9  -1.6  -1.3  -1.   -0.7  -0.4  -0.1   0.2   0.5
   0.8   1.1   1.4   1.7   2.    2.3   2.6   2.9   3.2   3.5   3.8   4.1
   4.4   4.7   5.    5.3   5.6   5.9   6.2   6.5   6.8   7.1   7.4   7.7
   8.    8.3   8.6   8.9   9.2   9.5   9.8]


На вход подается целое число b > 0. Создайте массив numpy, содержащий b чисел от 0 до pi включительно. Для генерации числа пи используйте numpy константу np.pi. Выведите массив на экран.

In [ ]:
import numpy as np
a=int(input())
arr=np.linspace(0,np.pi,a)
print(arr)

10
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


На вход подается целое число n>1. Создайте numpy массив, содержащий n первых чисел Фибоначчи, выведите его на экран.

In [ ]:
n=int(input())
arr=np.arange(0,n,1)
print(arr)

3
[0 1 2]


In [ ]:
fib1 = fib2 = 1
n = int(input())
print(fib1, fib2, end=' ')

for i in range(2, n):
    fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')


5
1 1 2 3 5 

In [ ]:
import numpy as np
fNumber = int(input())
a = np.arange(0, fNumber)
length_a = len(a)

sqrt_five = np.sqrt(5)
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrt_five))
print(Fn)

5
[0. 1. 1. 2. 3.]


На вход подается целое число n>0, cоздайте одномерный массив numpy, состоящий из n элементов, равных числу pi, и выведите его на экран.

In [ ]:
import numpy as np
n = int(input())
print(np.full(n, np.pi))

2
[3.14159265 3.14159265]


На вход подается строка слов, разделенных пробелом, создайте одномерный массив numpy, содержащий эти слова. Выведите массив на экран.

In [ ]:
import numpy as np
a=input()
arr=np.array(a.split())
print(arr)

sd dns sdksl sj
['sd' 'dns' 'sdksl' 'sj']


На вход подается строка, создайте одномерный массив numpy, содержащий символы этой строки. Выведите массив на экран

In [ ]:
import numpy as np
a=input()
list_1=list(a)
arr=np.array(list_1)
print(arr)

аро длы фвфыв98 фы_о
['а' 'р' 'о' ' ' 'д' 'л' 'ы' ' ' 'ф' 'в' 'ф' 'ы' 'в' '9' '8' ' ' 'ф' 'ы'
 '_' 'о']


На вход подается строка состоящая из слов, разделенных пробелом. Создайте одномерный массив, содержащий длины этих слов. Выведите массив на экран.

In [ ]:
import numpy as np
q = input()
word=q.split()
word_lengths = [len(word) for word in words]
arr=np.array(word_lengths)
print(arr)

аро длы фвфыв98 фы_о
[3 3 7 4]


На вход поступают две строки, состоящие из чисел, разделённых пробелом.

Необходимо создать два массива numpy a и b, в которые поместить эти числа. При этом нужно правильно определить какой тип использовать, исходя из данных, содержащихся в строках.

Затем на основе данных второго массива b необходимо создать третий c, значения которого взяты из второго массива b, а тип данных равен типу данных первого массива a.

Полученные три массива a, b, c вывести на экран в порядке их создания через пробел.

In [ ]:
import numpy as np
data_1=list(input())
data_2=list(input())
qs=data_1.dtype
qx=type(data_2)
print(qs, qx)

1 2 3
2.2 2 2


AttributeError: ignored

In [ ]:
import numpy as np
data_1=input()
data_2=input()
arr1 = np.fromstring(data_1, dtype=None, sep=" ")
arr2 = np.fromstring(data_2, dtype=None, sep=" ")
print(arr1, arr2)

1 2 3
2.2 2 2
[1. 2. 3.] [2.2 2.  2. ]


In [ ]:
import numpy as np
s1=np.array(input().split())
s2=np.array(input().split())
a=s1.dtype
b=s2.dtype
print (a, b)

1 2 3
2.2 2 2
<U1 <U3


In [ ]:
import numpy as np
data_1=input().split()
data_2=input().split()
for i in data_1:
  if i%1==0:
    data_1.astype(int)
  else:
    data_1
print(type(data_1))

1 2 3
2.2 2 2


TypeError: ignored

Напишите функцию convert_type(), которая принимает на вход одномерный numpy массив и возвращает новый массив того же размера, но с типом данных str.

Нужно только определить функцию, вызывать ее не нужно!

In [ ]:
import numpy as np
arr=np.array(str(input()))
print(type(arr))
print(arr)

2 3.3 5 5
<class 'numpy.ndarray'>
2 3.3 5 5


На вход подается целое число n.

Напишите программу, которая создает одномерный массив из n чисел, равномерно распределенных в диапазоне от 0 до 100 (включительно), и выводит в первой строке сам массив и в следующей строке его размерность, форму и количество элементов через пробел.ndim, shape и size.

In [ ]:
import numpy as np
arr=np.linspace(0, 100, int(input()))
print (arr)
print(arr.ndim, arr.shape, arr.size)

10
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
1 (10,) 10


На вход подается  строка действительных чисел разделенных пробелом. Напишите программу, которая создает одномерный массив из чисел, введенной строки с типом float16. Выведите на экран данный массив его тип и размер в байтах каждого элемента массива.

In [ ]:
import numpy as np
a=input().split()
arr=np.array(a)
num16 = np.float16(arr)
print(num16)
print (num16.dtype, num16.itemsize)

3.4 6 4.333
[3.4   6.    4.332]
float16 2


In [ ]:
import numpy as np
arr_fl = np.array(input().split(), dtype = np.float16)
print(arr_fl)
print(arr_fl.dtype, arr_fl.itemsize)

3.4 6 4.333
[3.4   6.    4.332]
float16 2


На вход подается строка целых чисел, разделенных пробелом, в которой содержится количество проданных за день билетов в течение прошедшей недели.

Создайте массив NumPy из этих данных, используйте тип int64. Выведите на экран сам массив в первой строке, среднее количество проданных за неделю билетов, округленное до трех знаков после запятой, и  тип данных массива через пробел во второй строке.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int64)
print(arr)
print(round(sum(arr)/len(arr),3), arr.dtype)

100 200 300 150 250 175 225
[100 200 300 150 250 175 225]
200.0 int64


На вход поступает строка целых чисел, разделенных запятой с пробелом, в которой записана температура в городе N за каждый день месяца.

Создайте массив numpy из данных о температуре в городе за каждый день месяца. Выведите на экран максимальную температуру в городе за месяц, размерность массива, его форму и тип, в одной строке, через пробел.

In [ ]:
import numpy as np
arr=np.array(input().split(', '), dtype=np.int32)
print (max(arr), arr.ndim, arr.shape, arr.dtype)

10, 15, 20, 25, 20, 18, 16, 21, 23, 22, 19, 14, 12, 11, 13, 17, 18, 19, 20, 22, 25, 27, 24, 23, 20, 18, 16, 12, 10, 11
27 1 (30,) int32


На вход поступает строка целых чисел, в которой содержатся данных о загрязнении воздуха за некоторый период времени.

Создайте массив numpy из данных о загрязнении воздуха. Выведите на экран количество дней в году, когда уровень загрязнения воздуха превышал норму. Нормой считайте значение 45.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
result=0
for i in arr:
  if i>45:
    result+=1
print(result)

33 57 87 51 31 31 87 37 65 98 91 41 29 59 43 41 68 39 65 17 11 66 1 74 77 91 79 54 43 19 41 4 45 9 36 55 86 29 29 18 71 90 68 40 39 57 63 24 24 13 32 48 27 3 28 95 19 64 42 60 33 86 23 96 54 1 25 49 79 94 77 44 44 79 53 66 25
37


Лесной гном собирает золотые яблоки, которые растут на деревьях в его лесу. Он создает массив numpy из количества яблок, которые он нашел на каждом дереве. Выведите на экран суммарное количество яблок, найденных гномом. Определите тип данных массива.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
print(sum(arr), arr.dtype)

40 12 28 4 7 38 21 9 3 5 42 26 34 4 7 12 36 22 22 6 35 19 4 44 32 38 7 11 30 26 5 33 7
669 int32


Маленький рыцарь отправляется на поиски драконьего гнезда. Он создает массив numpy из количества драконов в каждом гнезде, которые он обнаруживает в своем путешествии. Выведите на экран наименьшее количество драконов в гнезде и индекс гнезда с максимальным количеством драконов. Если ему повстречалось несколько гнезд с максимальным количеством драконов, выведите индекс первого встретившегося ему гнезда.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
max=arr.max()
list_1=list(arr)
q=list_1.index(max)
print (min(arr), q)

18 44 10 9 7 31 18 21 40 41 42 6 16 39 41 5 14 26 2 32 34 17 20 26 14 36 12 3 6 12 44 17 10
2 1


Пираты обнаруживают сундук с сокровищами на необитаемом острове. Они создают массив numpy из веса каждой монеты в сундуке, округляя вес каждой монеты до трех знаков после запятой. Выведите на экран суммарный вес сокровищ, которые они обнаружили, и определите тип данных массива.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.float64)
print (sum(arr), arr.dtype)

164.357 248.462 337.148 1.408 661.915 376.46 452.997 364.914 366.963 50.349 104.352 17.029 373.695 386.679 313.316 67.886 659.198 191.347 39.324 300.299 367.913 172.754 564.768 455.142 572.764 517.435 329.967 435.285 567.868 228.024 243.25 567.91 226.866
10728.044 float64


Принцесса хранит свои волшебные заклинания в заколдованном замке. Она создает массив NumPy из слов заклинания. Выведите на экран количество слов заклинания с нечетным количеством символов и количество слов заклинания, в которых больше 5 символов. Определите тип данных массива.

Слово - последовательность символов, разделенная пробелами.

In [ ]:
import numpy as np
arr=np.array(input().split())
res=0
res1=0
for i in arr:
  if len(i)>5:
    res+=1
for x in arr:
  if len(x)%2!=0:
    res1+=1
print(res1, res, arr.dtype)

Ветер времени взлетит, чтобы привнести силы в мою сущность, и я стану непобедимой в любой битве
14 5 <U11


Главный историк Средиземья ведет записи о событиях, происходящих в мире. Он создает массив numpy из объектов datetime, представляющих даты ключевых событий в истории мира. Выведите на экран тип данных массива, даты самого раннего и самого позднего событий.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=object)
print(arr.dtype, arr.min(), arr.max())

1598-04-29 1711-11-28 1661-05-06 0869-11-22 0930-05-22 0987-05-06 0827-05-22 1029-11-04 1255-02-12 1123-11-13 1697-03-17 1384-01-21 1408-06-10 1166-09-04 1109-09-18
object 0827-05-22 1711-11-28


Детектив Джо Ривера получил информацию о местонахождении опасного преступника по кличке Кармен. Он создает массив numpy из булевых значений, где True означает наличие признаков, свидетельствующих о присутствии Кармен на заданной территории. Определите тип данных массива и выведите на экран количество локаций, в которых может находиться Кармен.

In [ ]:
import numpy as np
arr=np.array(input().split())
ai=np.array(input().split(), dtype=bool)
res=[]
result=0
for i in arr:
  if i=='True':
    res.append(1)
  else:
    res.append(0)
for i in res:
  if i==1:
    result+=1
print(result, ai.dtype)

True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True
True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True
23 bool


In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=str)
arr=np.array(arr1, dtype=bool)
res=[]
result=0
for i in arr:
  if i=='True':
    res.append(1)
  else:
    res.append(0)
for i in res:
  if i==1:
    result+=1
print(arr,result, arr.dtype)

True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True


ValueError: ignored

Шерлок Холмс попросил вас создать массив numpy, в котором содержится информация о телефонных звонках, совершенных потенциальными жертвами серийного убийцы. На вход поступает строка в которой значение 1 в массиве означает, что звонок был совершен в момент времени, когда было совершена убийство. Значение 0 - звонок был совершен в другое время или не был совершен вообще. Создайте массив numpy на основе этой строки, содержащий данные за последний месяц в виде булевых значений. Выведите на экран количество звонков, которые совершались в моменты времени, когда были совершены убийства и тип данных массива, через пробел.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
sum=0
for i in arr:
  if i==1:
    sum+=1
print(sum)

1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0
0


In [ ]:
import numpy as np
a=list(input().split())
print (a)
arr=np.array(a,dtype=bool)
print(arr)

1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0
['1', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '0', '1', '1', '0', '0']
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


На вход поступают две строки, содержащие целые числа. Необходимо создать на их основе два массива numpy, объединить их, а затем повторить полученный массив три раза. Выведите на экран итоговый массив.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
arr3=np.concatenate((arr1,arr2))
arr3=np.repeat(arr3, 3)
print(arr3)

4 4 16 27 42 49 32 1 5 26 34 37 45 12 2 4 20 14 38 50
21 36 23 30 51 24 10 26 51 26 45 26 11 30 29 49 36 9 13 27
[ 4  4  4  4  4  4 16 16 16 27 27 27 42 42 42 49 49 49 32 32 32  1  1  1
  5  5  5 26 26 26 34 34 34 37 37 37 45 45 45 12 12 12  2  2  2  4  4  4
 20 20 20 14 14 14 38 38 38 50 50 50 21 21 21 36 36 36 23 23 23 30 30 30
 51 51 51 24 24 24 10 10 10 26 26 26 51 51 51 26 26 26 45 45 45 26 26 26
 11 11 11 30 30 30 29 29 29 49 49 49 36 36 36  9  9  9 13 13 13 27 27 27]


На вход поступают две строки. В первой строке содержится последовательность целых чисел, разделенных пробелом, во второй строке целое число i. Из первой строки нужно создать массив numpy и затем удалить из него с помощью функции delete() элемент с индексом i. Выведите на экран исходный и итоговый массивы, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input(), dtype=np.int32)
print (arr1)
arr1=np.delete(arr1, arr2)
print(arr1)

28 22 24 9 32 33 53 27 50 30 48 49
4
[28 22 24  9 32 33 53 27 50 30 48 49]
[28 22 24  9 33 53 27 50 30 48 49]


На вход поступают два числа a и b в одной строке, разделенные пробелом. Вам нужно создать массив numpy A чисел от a до b (b включительно, если оно нечетное), содержащий только нечетные числа. Затем создайте новый массив B путем повторения каждого элемента массива А дважды. Выведите на экран исходный A и итоговый массив B, каждый с новой строки.

In [ ]:
import numpy as np
a, b = map(int, input().split())
if b%2!=0:
  arr1=np.arange(a,b+1)
else:
  arr1=np.arange(a,b)
#print(arr1)
arr2=np.empty(0, dtype=int)
for i in arr1:
  if i%2!=0:
    arr2=np.append(arr2, i)
  else:
    arr2
print(arr2)
arr2=np.repeat(arr2,2)
print(arr2)

3 19
[ 3  5  7  9 11 13 15 17 19]
[ 3  3  5  5  7  7  9  9 11 11 13 13 15 15 17 17 19 19]


На вход поступают две строки, содержащие целые  числа, разделенные пробелом. На их основе создайте два одномерных масcива numpy a и b. Далее создайте третий массив c, который состоит из элементов массива a, затем из элементов массива b. Причем каждый элемент в массиве с повторяется 2 раза. Выведите на экран массивы a, b, c каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
arr3=np.concatenate((arr1,arr2)).repeat(2)
print(arr1)
print(arr2)
print(arr3)

19 34 39 -5 41 27 34 8
45 -5 12 6 48
[19 34 39 -5 41 27 34  8]
[45 -5 12  6 48]
[19 19 34 34 39 39 -5 -5 41 41 27 27 34 34  8  8 45 45 -5 -5 12 12  6  6
 48 48]


На вход поступает целое число n. Вам нужно создать массив a из n случайных действительных чисел равномерно распределенных в диапазоне от 0 до 1. Затем создайте массив b, увеличив размер массива a до 2n элементов с помощью функции resize(). Выведите на экран исходный массив a, итоговый массив b, каждый вывод с новой строки.

In [ ]:
import numpy as np
n = int(input())
np.random.seed(n)
arr1=np.random.rand(n)
arr2=np.resize(arr1, (2*n))
print(arr1, arr2, sep='\n')

10
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.77132064 0.02075195
 0.63364823 0.74880388 0.49850701 0.22479665 0.19806286 0.76053071
 0.16911084 0.08833981]


На вход поступает строка с целыми числами разделенными пробелами. На основе этой строки необходимо создать numpy массив а. Затем из массива а создайте массив b, в котором удалены все повторяющиеся элементы кроме первого. Порядок оставшихся элементов в массиве b должен совпадать с порядком этих элементов в массиве а. Выведите исходный массив а, итоговый b и тип элементов массива b, каждый вывод с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.empty(0, dtype=int)
for i in arr1:
  if i not in arr2:
    arr2=np.append(arr2, i)
  else:
    arr2
print(arr1)
print(arr2)
print(arr2.dtype)

4 5 2 3 5 3 5 2 3 2 3 5 4 5 2 4 3 3
[4 5 2 3 5 3 5 2 3 2 3 5 4 5 2 4 3 3]
[4 5 2 3]
int64


На вход поступают две строки. В первой содержатся целые числа, разделенные пробелом, во второй одно целое число n. На основе первой строки создать numpy массив a. Далее создать numpy массив b, в котором первым элементом является число n, далее следуют числа массива a. Массивы a и b вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input(), dtype=np.int32)
arr3=np.empty(0, dtype=int)
arr3=np.insert(arr1, 0, arr2)
print(arr1)
print(arr3)

2 24 17 23 29 23 18 26
-1
[ 2 24 17 23 29 23 18 26]
[-1  2 24 17 23 29 23 18 26]


На вход поступают две строки. В первой идут целые числа разделенные пробелом, во второй единственное целое число n. На основе чисел первой строки создайте массив a. Затем на основе массива a создайте массив b, в котором будут числа массива а > n. Порядок чисел в массиве b должен совпадать с порядком в массиве a. При этом типы элементов в массиве a и b должны быть одинаковыми. Выведите на экран массивы a и b, каждый с новой строки.

In [ ]:
import numpy as np
a=np.array(input().split(), dtype=np.int32)
#arr2=np.array(input(), dtype=np.int32)
c=int(input())
b=np.empty(0, dtype=np.int32)
for i in a:
  if i>c:
    b=np.append(b, i)
  else:
    b
print(a, b, a.dtype==b.dtype, sep='\n')

5 0 9 20 14 18 28 26 18 3
9
[ 5  0  9 20 14 18 28 26 18  3]
[20 14 18 28 26 18]
True


На вход поступают две строки. В первой строке расположены целые числа, разделенные пробелом. Во второй строке два целых числа start и end. Создайте массив a на основе чисел первой строки. Затем на основе массива a создайте массив b, который состоит из всех элементов массива a, кроме тех которые находятся на позициях от  start до end+1 не включительно. Выведите на экран массивы a и b каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
a, b = map(int, input().split())
print(arr1)
arr2=np.delete(arr1, np.arange(a,b+1))
print(arr2)

15 21 12 3 27 20 20 27 0 4
3 6
[15 21 12  3 27 20 20 27  0  4]
[15 21 12 27  0  4]


В первой строке поступает целое число n - количество массивов целых чисел, разделенных пробелом, которые поступают на вход в следующих n строках. В последней строке поступает целое число m - максимальное количество элементов в итоговом массиве. Необходимо объединить все массивы и создать массив numpy, назвав его a. Если количество элементов в них больше m, обрезать его. При этом тип итогового массива должен быть int64. Затем вывести итоговый массив на экран.

In [ ]:
import numpy as np
n=int(input())
a=np.array(input().split(), dtype=np.int64)
m=int(input())
a = a[:m]
print(a)
print(a.dtype)

4
22 -8 50 7 27 13 5 3 11 1 10 4 27 20 27 1 10 4 27 20 2 5
10
[22 -8 50  7 27 13  5  3 11  1]
int64


На вход поступает массив элементов, разделенных пробелом в первой строке, необходимо на его основе создать numpy массив a. Во второй строке дается название типа, к которому необходимо привести элементы массива а. Наконец в третьей строке последовательность целых чисел - индексы элементов которые нужно удалить из массива а. Выведите итоговый массив на экран.

In [ ]:
import numpy as np
arr1=np.array(input().split())
t=input()
arr3=np.array(input().split(), dtype=np.int64)
#print(arr1)
qqq=arr1.astype(t)
#print(qqq)
zzz=np.delete(qqq, arr3)
print(zzz)

1 2 3 4 5 6 7
int32
1 3 4
[1 3 6 7]


На вход поступают три строки. В первой и второй строках - числа (действительные или целые), разделенные пробелом. Необходимо на их основе создать два numpy массива a и b. В третьей строке целое число n - размер итогового массива. Необходимо объединить массивы a и b, привести тип элементов получившегося массива к типу элементов первого массива а и привести размер получившегося массива к n. Вывести итоговый массив на экран.

In [ ]:
import numpy as np
s1=input().split()
s2=input().split()
n=int(input())
if '.' in s1[1]:
    arr1=np.array(s1,dtype=np.float64)
else:
    arr1=np.array(s1,dtype=np.int32)
if '.' in s2[1]:
    arr2=np.array(s2,dtype=np.float64)
else:
    arr2=np.array(s2,dtype=np.int32)
tp=arr1.dtype
qq=arr2.astype(tp)
arr3=np.concatenate((arr1,qq))
resized_arr=np.resize(arr3, (n,))
print(resized_arr)




12 3 1 8 9 3 5 3 11 0 11 11 7 8
5.814 18.797 21.87 6.032 3.065 3.861 9.439 11.137 3.36 16.504
18
[12  3  1  8  9  3  5  3 11  0 11 11  7  8  5 18 21  6]


Три мушкетера - Атос, Портос и Арамис - решили объединить свои одномерные массивы numpy целых чисел в один массив. Однако у каждого мушкетера есть свой массив разного размера. Помогите им объединить свои массивы в один массив, используя функцию concatenate.

In [ ]:
import numpy as np
s1=np.array(input().split(), dtype=np.float16)
s2=np.array(input().split(), dtype=np.float16)
s3=np.array(input().split(), dtype=np.float16)
arr1=np.concatenate((s1,s2, s3))
print(arr1)


12 3 1 8 9 3 5 3 11
22 -8 50 7 27
8 9 3 5 4 5 6
[12.  3.  1.  8.  9.  3.  5.  3. 11. 22. -8. 50.  7. 27.  8.  9.  3.  5.
  4.  5.  6.]


В первой строке поступает целое число n - количество массивов с числами, разделенными пробелами. Во второй строке - название типа к которому нужно привести элементы всех массивов, далее в следующих n строках идут сами массивы.  В последней строке идет целое число m - количество элементов, которое должно быть в каждом из массивов. Привести тип элементов всех массивов к необходимому типу, также привести размерность каждого массива к типу n, если при этом размерность нового массива больше, чем исходного, лишние значения заполнить нулями. Вывести все получившиеся массивы на экран через пробел.

In [ ]:
import numpy as np
cnt=int(input().split())
form=input().split()
arr=np.array(input().split())
count_el=input().split()


В древнем доме на окраине города, где жил исследователь мистических артефактов, был обнаружен таинственный массив. Символы на массиве были написаны на древнем языке, и никто не мог прочитать их. Однако массив был наделен темной магией, и когда исследователь начал изучать его, массив начал расширяться и превращаться в портал в иной мир. Помогите исследователю уменьшить размеры массива, используя функцию resize, чтобы остановить его расширение и предотвратить открытие портала в темный мир. Однако, будьте осторожны, вам придется преодолеть множество трудностей и противостоять неизвестным силам, чтобы остановить этот зловещий массив.

In [ ]:
import numpy as np
arr=np.array(input().split())
#arr1=np.resize(arr, 5)
#print(arr1)
arr.resize(5)
print(arr)

4 3 2 12 11 1 4 3 7 11 1 10 2 10 3 8 6 7 7 7 7 6 5 4 7 0 7 5 0 6 9 4 5 5 0 3 12 1 9 1 2 3 8 5 5
['4' '3' '2' '12' '11']


На вход поступает строка целых чисел, разделенных пробелом. Создайте на ее основе numpy массив а. Затем  создайте новый массив b, содержащий только первые 5 элементов исходного массива. Оба массива выведите на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[:5])
print(arr1)
print(arr2)

30 3 12 8 9 10 3 3 14 16
[30  3 12  8  9 10  3  3 14 16]
[30  3 12  8  9]


На вход поступает последовательность действительных чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий только последние 3 элемента исходного массива. Оба массива вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float32)
arr2=np.array(arr1[::-1])
q=arr2[:3]
r=q[::-1]
print(arr1)
print(r)

24 24 15 2 19 4 30 16 32 30
[24. 24. 15.  2. 19.  4. 30. 16. 32. 30.]
[16. 32. 30.]


In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float32)
arr2=np.array(arr1[-3:])
print(arr1)
print(arr2)

24 24 15 2 19 4 30 16 32 30
[24. 24. 15.  2. 19.  4. 30. 16. 32. 30.]
[16. 32. 30.]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий все элементы исходного массива в обратном порядке. Оба массива вывести на экран, каждый с новой строки

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[::-1])
print(arr1)
print(arr2)

24 24 15 2 19 4 30 16 32 30
[24 24 15  2 19  4 30 16 32 30]
[30 32 16 30  4 19  2 15 24 24]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий только элементы исходного массива с нечетными индексами. Оба массива вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[1::2])
print(arr1)
print(arr2)

20 8 3 25 16 9 16 20 2 10
[20  8  3 25 16  9 16 20  2 10]
[ 8 25  9 20 10]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий элементы исходного массива, кроме первых 3 и последних 2. Оба массива вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[3:-2])
print(arr1)
print(arr2)

3 27 1 11 0 26 23 16 21 11 5
[ 3 27  1 11  0 26 23 16 21 11  5]
[11  0 26 23 16 21]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий все элементы исходного массива, с индексами кратными 3. Оба массива вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[::3])
print(arr1)
print(arr2)
#b = np.array([a[i] for i in range(len(a)) if i % 3 == 0])

17 0 10 17 23 8 28 16 14 7 31 7 17 21 22 5 31 31 8 6 16 20 26 23 31
[17  0 10 17 23  8 28 16 14  7 31  7 17 21 22  5 31 31  8  6 16 20 26 23
 31]
[17 17 28  7 17  5  8 20 31]


На вход поступает две строки, содержащие одинаковое количество целых чисел, разделенных пробелом. На их основе создать список numpy, состоящий из элементов, которые находятся на четных позициях первого списка, затем следуют элементы, стоящие на нечетных позициях второго списка. Если длина списков нечетная, то последний элемент не учитывается. Полученный список вывести на экран.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
if len(arr1)%2!=0 and len(arr2)%2!=0:
  g=arr1[:-1]
  b=arr2[:-1]
else:
  g=arr1
  b=arr2
arr1_1=np.array(g[::2])
arr2_2=np.array(b[1::2])
arr_rez=np.concatenate((arr1_1,arr2_2))
print(arr_rez)


27 22 24 1 26 20 6 14 31 7 31
83 92 1 49 43 45 78 6 27 33 27
[27 24 26  6 31 92 49 45  6 33]


Золушка готовится к балу, но у нее нет подходящих туфель. Ей нужно найти туфли, которые подойдут по размеру, а размер у нее это целое число, которое поступает на вход в первой строке. Во второй строке поступает массив, в котором каждый элемент - это размер туфель. Найдите все туфли, которые подходят Золушке. В качестве ответа выведите numpy массив из индексов туфель, которые подходят Золушке.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
result = np.where(arr2 == arr1)
print(result[0])

33
37 37 40 36 36 41 36 42 40 36 39 36 41 36 41 34 33 35 41 37 35
[16]


Вы исследуете древний храм, где вам нужно разгадать загадку, чтобы достать древний артефакт. Загадка представляет собой одномерный массив, который нужно перевернуть задом наперед, чтобы получить правильный ответ. Вы можете использовать срезы одномерных массивов numpy, чтобы перевернуть массив и раскрыть тайну.

In [ ]:
import numpy as np
sl=list(input())
sl.reverse()
arr=np.array(sl)
print(arr)

имактеверксордеввлапуток
['к' 'о' 'т' 'у' 'п' 'а' 'л' 'в' 'в' 'е' 'д' 'р' 'о' 'с' 'к' 'р' 'е' 'в'
 'е' 'т' 'к' 'а' 'м' 'и']


Волшебная рыбка просит вас помочь ей отсортировать массив чисел. Она хочет, чтобы вы взяли первые 5 элементов массива и отсортировали их по убыванию. Затем вы должны взять последние 3 элемента массива и отсортировать их по возрастанию. Затем выведите получившийся массив в виде чисел, разделенных пробелом, на экран. Если вы выполните ее просьбу, она исполнит любое ваше желание.

In [ ]:
import numpy as np
a = np.array(input().split(), dtype=np.int32)
b = sorted(a[:5], reverse=True)
c = sorted(a[-3:])
d = np.concatenate((b, c))
print(*d)

37 41 37 37 41 38 33 37 38 41 3
41 41 37 37 37 3 38 41


In [ ]:
import numpy as np
sl=np.array(input().split(), dtype=np.int32)
sl_left=sl[:5]
sl_right=sl[-3:]
q=-np.sort(-sl_left)
a=np.sort(sl_right)
rez=np.concatenate((q,a))
rezz=' '.join(map(str, rez))
print(rezz)

37 41 37 37 41 38 33 37 38 41 3
41 41 37 37 37 3 38 41


Колдунья дала вам массив чисел и просит вас изменить его содержимое. Она хочет, чтобы вы взяли каждый второй элемент массива, начиная со второго, и заменили их на 0. Затем она хочет, чтобы вы взяли последние 3 элемента массива и заменили их на 1. Отдайте ей итоговый массив.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int64)
b=np.empty(0, dtype=np.int64)
for i in arr:
  if arr[i]%2!=0:
    np.append(b,0)
  else:
    np.append(b,i)
print (b)

37 39 37 41 37 37 41 38 33 37 38 41 34 41 40 39 36 34 37 34 39 33 39 35 42 42 36


IndexError: ignored

Сказочная змея просит вас помочь ей с ее массивом. Она хочет, чтобы вы взяли первые 3 элемента массива и поместили их в новый массив. Затем вы должны взять каждый 4-ый элемент массива, начиная с четвертого и поместить его в тот же новый массив. Наконец, она хочет, чтобы вы взяли последние 4 элемента массива и поместили их в конец нового массива. После этого отдайте ей получившийся массив и она сможет заснуть на следующие 1000 лет.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int64)
left_3=arr[:3]
mid_arr=arr[3::4]
last_arr=arr[-4:]
arr_rez=np.concatenate((left_3,mid_arr,last_arr))
print(arr_rez)

11 27 32 23 21 22 21 15 13 28 2 30 17 16 1 20 25 40 13 41 14 23 25 36 12 4 15
[11 27 32]
[23 15 30 20 41 36]
[36 12  4 15]
[11 27 32 23 15 30 20 41 36 36 12  4 15]


Ваша команда исследователей работает над проектом, который требует анализа большого количества данных. Один из массивов данных, называемый data, содержит результаты эксперимента для каждого участника. Вам нужно вывести срез массива, который содержит все результаты, кроме первых 5 и тех которые стоят на местах индексы которых кратны 3.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int64)
del_5=arr[5:]
print(del_5)

18 16 19 20 26 29 20 9 6 16 25 15 6 25 23 23 29 22 17 21 19 28 18 17 18 21 28 28 24 5 10 11 8 8 9 14 28 13 31 18 29 20 32 25 13 5 7 11 31 31 11 29 7 6 18 30 25 22 15 24 24 16 18 6 5 15 25 32 13 19 11 13 30 23 6 9 15 7 8 9 29 23 29 22 5 31 11 15 22 17 12 16 14 28 7 29 24 15 10 25 21 5 22 24 15 6 17 12 11 24 30 14 23 12 21 8 20 17 32 26
[29 20  9  6 16 25 15  6 25 23 23 29 22 17 21 19 28 18 17 18 21 28 28 24
  5 10 11  8  8  9 14 28 13 31 18 29 20 32 25 13  5  7 11 31 31 11 29  7
  6 18 30 25 22 15 24 24 16 18  6  5 15 25 32 13 19 11 13 30 23  6  9 15
  7  8  9 29 23 29 22  5 31 11 15 22 17 12 16 14 28  7 29 24 15 10 25 21
  5 22 24 15  6 17 12 11 24 30 14 23 12 21  8 20 17 32 26]


In [ ]:
[29  9  6 25 15 25 23 29 22 21 19 18 17 21 28 24  5 11  8  9 14 13 31 29
 20 25 13  7 11 31 11  7  6 30 25 15 24 16 18  5 15 32 13 11 13 23  6 15
  7  9 29 29 22 31 11 22 17 16 14  7 29 15 10 21  5 24 15 17 12 24 30 23
 12  8 20 32 26]

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
for i in arr:
  if arr[i]%3==0:
    b=np.append(b, i)
    print(b)


18 16 19 20 26 29 20 9 6 16 25 15 6 25 23 23 29 22 17 21 19 28 18 17 18 21 28 28 24 5 10 11 8 8 9 14 28 13 31 18 29 20 32 25 13 5 7 11 31 31 11 29 7 6 18 30 25 22 15 24 24 16 18 6 5 15 25 32 13 19 11 13 30 23 6 9 15 7 8 9 29 23 29 22 5 31 11 15 22 17 12 16 14 28 7 29 24 15 10 25 21 5 22 24 15 6 17 12 11 24 30 14 23 12 21 8 20 17 32 26
[19]
[19 25]
[19 25 25]
[19 25 25 22]
[19 25 25 22 19]
[19 25 25 22 19 28]
[19 25 25 22 19 28 28]
[19 25 25 22 19 28 28 28]
[19 25 25 22 19 28 28 28 24]
[19 25 25 22 19 28 28 28 24 11]
[19 25 25 22 19 28 28 28 24 11  8]
[19 25 25 22 19 28 28 28 24 11  8  8]
[19 25 25 22 19 28 28 28 24 11  8  8 28]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7 25]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7 

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
for i in arr:
  if arr[i]%3==0:
    b=np.append(b, i)
    print(b)

18 16 19 20 26 29 20 9 6 16 25 15 6 25 23 23 29 22 17 21 19 28 18 17 18 21 28 28 24 5 10 11 8 8 9 14 28 13 31 18 29 20 32 25 13 5 7 11 31 31 11 29 7 6 18 30 25 22 15 24 24 16 18 6 5 15 25 32 13 19 11 13 30 23 6 9 15 7 8 9 29 23 29 22 5 31 11 15 22 17 12 16 14 28 7 29 24 15 10 25 21 5 22 24 15 6 17 12 11 24 30 14 23 12 21 8 20 17 32 26
[19]
[19 25]
[19 25 25]
[19 25 25 22]
[19 25 25 22 19]
[19 25 25 22 19 28]
[19 25 25 22 19 28 28]
[19 25 25 22 19 28 28 28]
[19 25 25 22 19 28 28 28 24]
[19 25 25 22 19 28 28 28 24 11]
[19 25 25 22 19 28 28 28 24 11  8]
[19 25 25 22 19 28 28 28 24 11  8  8]
[19 25 25 22 19 28 28 28 24 11  8  8 28]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7 25]
[19 25 25 22 19 28 28 28 24 11  8  8 28 25  7 11 11  7 

In [ ]:
[29  9  6 25 15 25 23 29 22 21 19 18 17 21 28 24  5 11  8  9 14 13 31 29
 20 25 13  7 11 31 11  7  6 30 25 15 24 16 18  5 15 32 13 11 13 23  6 15
  7  9 29 29 22 31 11 22 17 16 14  7 29 15 10 21  5 24 15 17 12 24 30 23
 12  8 20 32 26]

Вы работаете в научной лаборатории, изучающей погоду на различных континентах. У вас есть массив temperatures, содержащий средние температуры для каждого месяца на протяжении года. Вам нужно вывести срез массива, который содержит температуры только для зимних месяцев (декабрь, январь, февраль). Данные в массиве начинаются с января.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
qq=arr[0:2]
zz=arr[-1:]
arr_rez=np.concatenate((zz,qq))
print(arr_rez)

-12 -19 -5 5 12 23 27 25 19 12 3 -19
[-19 -12 -19]


Вы отправляетесь в путешествие по пустыне, но у вас есть только один компас, который показывает направление на север. Вы решили использовать массив directions, который представляет собой последовательность чисел, где 0 означает движение на север, 1 - на восток, 2 - на юг и 3 - на запад. Вам нужно создать новый массив north_directions, который будет содержать только те значения массива directions, которые означают движение на север. Вам нужно вывести каждое второе из значений нового массива.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
for i in arr:
  if i==0:
    b=np.append(b,i)
print(b[1::2])

1 3 2 2 1 3 2 3 2 2 0 3 2 1 2 2 0 0 0 1 3 3 0 3
[0 0]


Входные данные: На вход поступают две строки. В первой строки находится целое число n, означающее день недели с которого начинаются записи в массиве, который поступает во второй строке. 0 - воскресенье, 1 - понедельник, 2 -вторник и т.д. Тренировки проходят каждый день.

In [ ]:
import numpy as np
d=int(input())
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
if d==0:
  b=np.append(b,arr[::7])
elif d==1:
  b=np.append(b,arr[1::7])
elif d==2:
  b=np.append(b,arr[2::7])
elif d==3:
  b=np.append(b,arr[3::7])
elif d==4:
  b=np.append(b,arr[4::7])
elif d==5:
  b=np.append(b,arr[5::7])
else:
  b=np.append(b,arr[6::7])
print(b)

2
76 55 60 81 87 84 71 52 79 86 84 83 76 72 69 71 99 84 90 82 62 71 56 78 59 97 77 78 85 73 60 72 52 64 95 57 79 88 51 58 50 81 61 68 51 76 82 67 58 82 80 70 95 82 87 66 68 91 59 53 79 58 91 81 67 58 56 76 54 85 88 73 79 68 50 80 70
[60 86 99 78 60 88 51 70 59 58 79]


In [ ]:
import numpy as np
d=int(input())
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
if d==0:
  b=np.append(b,arr[::7])
elif d==1:
  b=np.append(b,arr[::7])
elif d==2:
  b=np.append(b,arr[5::7])
elif d==3:
  b=np.append(b,arr[::7])
elif d==4:
  b=np.append(b,arr[::7])
elif d==5:
  b=np.append(b,arr[::7])
else:
  b=np.append(b,arr[::7])
print(b)

2
76 55 60 81 87 84 71 52 79 86 84 83 76 72 69 71 99 84 90 82 62 71 56 78 59 97 77 78 85 73 60 72 52 64 95 57 79 88 51 58 50 81 61 68 51 76 82 67 58 82 80 70 95 82 87 66 68 91 59 53 79 58 91 81 67 58 56 76 54 85 88 73 79 68 50 80 70
[84 76 82 77 64 50 67 87 58 54 80]


Напишите функцию reverse_array(arr), которая принимает на вход одномерный массив arr и возвращает новый массив с элементами arr, расположенными в обратном порядке.

Функцию вызывать не нужно, просто создайте ее.

In [ ]:
import numpy as np
def reverse_array(arr):
  return arr[::-1]
reverse_array(np.array(input().split(), dtype=np.int32))

76 55 60 81 87 84 71 52 79 86 84 83 76 72 69 71 99 84 90 82 62


array([62, 82, 90, 84, 99, 71, 69, 72, 76, 83, 84, 86, 79, 52, 71, 84, 87,
       81, 60, 55, 76], dtype=int32)

Напишите функцию swap_first_last(arr), которая принимает на вход одномерный массив arr и возвращает новый массив, в котором первый и последний элементы поменялись местами.

In [ ]:
import numpy as np
def swap_first_last(arr):
  e=arr[1:-1]
  z=arr[:1]
  b=arr[-1:]
  arr_rez=np.concatenate((b,e,z))
  return arr_rez
reverse_array(np.array(input().split(), dtype=np.int32))

0 82 62 71 56 78 59 97 77 78 85 73 60 72 52 64 95 5


array([ 5, 95, 64, 52, 72, 60, 73, 85, 78, 77, 97, 59, 78, 56, 71, 62, 82,
        0], dtype=int32)

Напишите функцию slice_replace(arr, start, end, replacement), которая принимает на вход список arr, начальный и конечный индексы среза start и end, а также новый список replacement, который будет использоваться для замены элементов из среза arr[start:end]. Функция должна возвращать новый NumPy массив, в котором элементы среза arr[start:end] заменены на элементы среза списка replacement[start:end].

При этом

Если start > last_index, где last_index - последний индекс массива arr, и start<last_index_replacement,  то элементы среза replacement[start:end] добавляются в конец массива arr.

Если start > last_index_replacement, то массив arr возвращается без изменений.

In [ ]:
import numpy as np
def slice_replace(arr, start, end, replacement):
  last_index_arr=len(arr)
  last_index_replace=len(replacement)
  if start>=last_index_arr and start<last_index_replace:
    arr_1_rez=np.concatenate((arr, replacement[start:end]))
  elif start>last_index_replace and start>last_index_arr:
    arr_1_rez=arr
  elif start==0:
    arr_1_rez=np.concatenate((replacement[start:end],arr[end:]))
  else:
    arr_1_rez=np.concatenate((arr[:start],replacement[start:end]))
  return arr_1_rez

slice_replace(np.array(input().split(), dtype=np.int32), int(input()), int(input()), np.array(input().split(), dtype=np.int32))

1 2
5 
10
3 4


array([1, 2], dtype=int32)

Имеется массив зарплат сотрудников компании, в котором каждому индексу отвечает определенный работник, а значением является зарплата, и необходимо изменить зарплату определенных сотрудников. На вход, в первой строке, поступает массив со старой зарплатой сотрудников, во второй строке - массив индексов сотрудников, зарплату которых нужно изменить. В третьей строке поступает массив с новыми значениями зарплат. На выход подайте обновленный массив numpy с обновленными данными по зарплате.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
ind=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
updated_salaries = np.copy(arr1)
for i, salary in enumerate(arr2):
  updated_salaries[ind[i]] = salary
  print(i, salary)
  print(updated_salaries)

76 55 60 81 87 84 71 52 79 86 84 83 76
0 2 7
88 65 78
0 88
[88 55 60 81 87 84 71 52 79 86 84 83 76]
1 65
[88 55 65 81 87 84 71 52 79 86 84 83 76]
2 78
[88 55 65 81 87 84 71 78 79 86 84 83 76]


In [ ]:
import numpy as np
def update_salaries(old_salaries, indexes_to_update, new_salaries):
    updated_salaries = np.copy(old_salaries)
    for i, salary in enumerate(new_salaries):
        updated_salaries[indexes_to_update[i]] = salary
    return updated_salaries


update_salaries(np.array(input().split(), dtype=np.int32),np.array(input().split(), dtype=np.int32),np.array(input().split(), dtype=np.int32))

76 55 60 81 87 84 71 52 79 86 84 83 76
0 2 7
88 65 78


array([88, 55, 65, 81, 87, 84, 71, 78, 79, 86, 84, 83, 76], dtype=int32)

На Земле произошел вирусный апокалипсис, и многие люди стали зомби. Но ученые нашли лекарство от вируса зомби, которое можно найти в определенной позиции в одномерном numpy массиве, содержащем последовательность чисел. Но лекарство сильно портится от света, поэтому нужно заменить все числа в массиве, кроме позиции с лекарством, на число -1, чтобы его не испортить.

На вход поступает целое число n - идентификатор лекарства в массиве, который поступает во второй строке. Необходимо вернуть массив в соответствии с условиями задачи.

In [ ]:
import numpy as np
id_l=np.array(input().split(), dtype=np.int32)
arr=np.array(input().split(), dtype=np.int32)
for i, ind in enumerate(arr):
  #print(i, ind)
  if i!=id_l:
    arr[i]=-1
print(arr)


6
53 79 58 91 81 67 58 56 76 54
0 53
1 79
2 58
3 91
4 81
5 67
6 58
7 56
8 76
9 54
[-1 -1 -1 -1 -1 -1 58 -1 -1 -1]


Компания хочет сделать резервную копию важных данных на дополнительном жестком диске, но не хочет рисковать потерей данных, если что-то пойдет не так. Чтобы обезопасить себя, компания создаст копию одномерного numpy массива, содержащего информацию о данных, и заменит в копии все значения, которые являются конфиденциальной информацией, на случайные значения. Таким образом, можно создать безопасную архивную копию, не рискуя утечкой данных.

На вход подается массив целых чисел, разделенных пробелом - а. Во второй строке подается массив индексов значений в массиве а которые нужно изменить. В третьей строке подаются новые значения, соответствующие этим индексам. На выход необходимо подать старый numpy массив а с первоначальными значениями и новую его копию с измененными данными.

In [2]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
ind=np.array(input().split(), dtype=np.int32)
arr_new=np.array(input().split(), dtype=np.int32)
updated_arr = np.copy(arr)
for i, q in enumerate(arr_new):
  updated_arr[ind[i]] = q
print(arr)
print(updated_arr)

82 80 70 95 82 87 66 68 91 59 53 79 58 91
0 1 4 5
8 8 8 8 
[82 80 70 95 82 87 66 68 91 59 53 79 58 91]
[ 8  8 70 95  8  8 66 68 91 59 53 79 58 91]


Написать функцию multpl(arr1, arr2), которая на вход принимает два одномерных numpy массива arr1 и arr2 и возвращает новый массив, содержащий результат их поэлементного сложения. Функцию вызывать не нужно, просто создайте ее.

In [4]:
import numpy as np
def multpl(arr1, arr2):
  c=arr1+arr2
  return c
multpl(np.array(input().split(), dtype=np.int32),np.array(input().split(), dtype=np.int32))

86 84 83 76 72 69 71 99
86 84 83 76 72 69 71 99


array([172, 168, 166, 152, 144, 138, 142, 198], dtype=int32)

В глубинах океана живет золотая рыбка, которая обладает волшебной способностью умножать и делить числа. Однажды, капитан корабля потерял свои карты, на которых были указаны координаты пути к сокровищам. Он обратился за помощью к золотой рыбке, и она согласилась помочь, но только если капитан даст ей массив чисел. Золотая рыбка умножит каждый элемент массива на 3 и разделит на 2, затем к результату каждой операции добавит 10. После этого она вернет массив обратно капитану, а он должен будет найти индексы элементов, которые меньше среднего значения всех элементов и вывести их на экран, вместе с итоговым массивом каждый с новой строки.

На вход поступает строка чисел, разделенных пробелом, на основе которой нужно создать массив numpy  и произвести с ним манипулации в соответсвии с условием задачи.

In [17]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
b=np.empty(0, dtype=np.int32)
arr1=np.copy(arr)
sm=sum(arr1)/len(arr1)
for i,ind in enumerate(arr1):
  if ind<sm:
    b=np.append(b,i)
print(list(b))
op=arr1*3/2+10
print(op)

0 38 93 15 65 4 87 99 17 51 84 13 78 45 85 14 10 22 23 68 88 28 65
[0, 1, 3, 5, 8, 11, 13, 15, 16, 17, 18, 21]
[ 10.   67.  149.5  32.5 107.5  16.  140.5 158.5  35.5  86.5 136.   29.5
 127.   77.5 137.5  31.   25.   43.   44.5 112.  142.   52.  107.5]


В далеком царстве есть сад, в котором растут фрукты разных видов. Каждый фрукт имеет свой цвет, который соответствует определенному числу. Сад зачарован, и фрукты каждый день увеличивают свою массу на 20%, а цвет становится ярче на 15%. Царь хочет знать, через сколько дней цвет каждого фрукта превысит определенную отметку, равную 100. Помогите царю узнать это и выведите на экран целое число - количество дней, спустя которое цвет каждого фрукта станет не менее 100, в следующей строке выведите итоговый массив со значениями цветов каждого фрукта спустя данный промежуток времени.

На вход поступает строка действительных чисел, разделенных пробелом, значение каждого числа - цвет соответствующего фрукта в условных единицах.

In [88]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
minim=min(arr)
i=0
arr_sb=0
while minim<100:
  arr_sb+=arr*1.15
  minim=minim*1.15
  i+=1
print(i, minim, arr_sb)


2 10 16 14 20 24 28 8 29 9 13 23 29 6 28 10
28 100.13122413124505 [ 64.4 322.  515.2 450.8 644.  772.8 901.6 257.6 933.8 289.8 418.6 740.6
 933.8 193.2 901.6 322. ]


В темном лесу живет мудрый маг, у которого есть магическая палочка. Она умеет возводить числа в любую положительную степень. Однажды маг решил проверить свои способности и дал своей палочке массив чисел. Он возвел каждый элемент в квадрат, затем в третью степень, затем в четвертую, и так далее, пока не достиг 6-й степени. После этого маг собрал все числа, полученные в результате операций, в новый массив и хочет узнать, какое из чисел является наименьшим.

На вход подается строка действительных чисел, разделенных пробелом. На выход нужно подать число, соответствующее условию задачи и исходный массив после преобразований.

In [99]:
import numpy as np
arr=np.array(input().split(), dtype=np.float64)
step=0
while step<6:
  a=arr**2
  b=a**3
  c=b**4
  d=c**5
  e=d**6
  step+=1
print(min(e))
print(e)

2 1.5 1.2 2.1 2 1.5
1.0244650674915638e+57
[5.51565226e+216 6.10529313e+126 1.02446507e+057 9.95158389e+231
 5.51565226e+216 6.10529313e+126]


In [100]:
import numpy as np
arr = np.array(input().split(), float)
for i in range(2, 7):
    arr = arr ** i
print(arr.min())
print(arr)

2 1.5 1.2 2.1 2 1.5
1.0244650674915638e+57
[5.51565226e+216 6.10529313e+126 1.02446507e+057 9.95158389e+231
 5.51565226e+216 6.10529313e+126]


В музее были украдены драгоценные украшения, и детективу нужно вычислить, сколько украшений было украдено и сколько они стоили. Для этого детективу нужно создать массивы, содержащие количество и цену каждого украшения в музее. Затем детектив может использовать операцию умножения, чтобы вычислить общую стоимость каждого типа украшений, и операцию сложения, чтобы найти общую стоимость всех украденных украшений.

На вход подаются две строки целых чисел разделенных пробелом count_arr и price_arr - количество и цена каждого украшения в музее. На выход необходимо подать общую сумму украденного.

In [102]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float32)
arr2=np.array(input().split(), dtype=np.float32)
z=int(sum(arr1*arr2))
print(z)

1 1 1 1
2 2 2 2
8


Напишите функцию func1(a, b), которая принимает два одномерных массива a и b и возвращает новый массив, в котором на каждой позиции i находится результат операции a[i] > b[i] & a[i] != 0. Вызывать функцию не надо, только определите ее.

In [107]:
import numpy as np
def func1(a, b):
  return np.all(a>b&a!=0)


func1(np.array(input().split(), dtype=np.int32),np.array(input().split(), dtype=np.int32))

1 6 2 2 4 4
6 5 3 3 2 4


ValueError: ignored

Вы проводите медицинские исследования и хотите определить, какой из двух лекарственных препаратов более эффективен для лечения конкретного заболевания. Для этого вам поступают два одномерных массива а, b с показателями здоровья пациентов, которые получали каждый из препаратов. Вам необходимо сделать вывод о том какой препарат более эффективен а или b.

Более эффективным препаратом считать тот для которого больше количество показателей здоровья превышающих аналогичные показатели для другого лекарства. Например если в первом массиве значения [ 1 2 1] а во втором [10 1 0], то более эффективным считается первый препарат, так как для него два показателя здоровья выше, чем у второго препарата. В качестве ответа вывести а если эффективнее первый препарат, в противном случае b. Гарантируется, что какой-то один из препаратов эффективнее.

In [123]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
#print(sum(arr1>arr2))
#print(sum(arr1<arr2))
if sum(arr1>arr2)>sum(arr1<arr2):
  print('a')
else:
  print('b')

1 2 3 4
2 3 4 1
b


Два дракона, красный и зеленый, соревнуются между собой, совершая различные трюки. Красный дракон совершает n трюка в день и получает за каждый трюк m очков. Зеленый дракон совершает i трюков в день и получает за каждый трюк j очков. Кто из драконов наберет больше очков за N дней?

На вход поступает 5 чисел в одной строке через пробел: n, m, i, j, N.

В качестве ответа необходимо вывести слово "зеленый", "красный" или "ничья" без кавычек. Необходимо воспользоваться возможностями библиотеки numpy для решения данной задачи.

In [131]:
import numpy as np
n,m,i,j,N=map(int,(input().split()))
sum_1=n*m*N
sum_2=i*j*N
if sum_1>sum_2:
  print ('красный')
elif sum_1<sum_2:
  print ('зеленый')
else:
  print ('ничья')

5 5 3 3 12
красный


Том Сойер и его друг соревнуются в беге. Напишите функцию find_faster_runner(tom_speed, friend_speed), которая принимает на вход два одномерных массива NumPy tom_speed и friend_speed, содержащие скорости Тома и его друга соответственно в различных забегах. Функция возвращает строку "Tom" , если Том победил хотя бы в одном забеге и строку "Friend" если Том ни разу не превзошел своего друга. Если скорости обоих бегунов всегда равны, функция должна вернуть строку "Draw".

In [160]:
import numpy as np
def find_faster_runner(tom_speed, friend_speed):
  sm=sum(np.greater(tom_speed,friend_speed))
  eq=np.equal(tom_speed,friend_speed)
  if sm>0:
    return 'Tom'
  elif np.all(eq)==True:
    return 'Draw'
  else:
    return 'Friend'

find_faster_runner(np.array(input().split(), dtype=np.int32),np.array(input().split(), dtype=np.int32))

1 2 3 2 4 5 2 3
2 2 4 5 5 6 3 1


'Tom'

Однако, чтобы найти этот массив "С", тебе нужно выполнить трудную задачу - найти сокровища, спрятанные в глубинах твоего собственного разума. Ведь Колдун сказал, что "С" равняется "А" плюс "Б", деленное на "А".

Так что, если ты жаждешь открыть эту тайну, то тебе нужно взять свою мудрость и умение решить эту задачу с помощью массивов numpy.

In [166]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float64)
arr2=np.array(input().split(), dtype=np.float64)
rez=arr1+(arr2/arr1)
print(rez)

12.55 0.87 6.33 10.16 17.14 3.48 24.53 15.62 4.87 23.22 5.13 16.63 12.09 6.73
6.23 24.73 11.11 4.63 12.02 6.46 24.81 24.31 0.06 4.66 10.15 7.3 19.01 8.12
[13.04641434 29.29528736  8.08513428 10.61570866 17.84128355  5.33632184
 25.54141459 17.17633803  4.88232033 23.42068906  7.1085575  17.06896572
 13.66237386  7.93653789]


Из глубин математических абсолютностей возвышалось зловещее знамение - система двух уравнений, связывающих переменные "х" и "у". Странные символы "а", "b", "c", "d", "e" и "f", написанные на языке чисел, вопили о помощи, вызывая из тьмы таинственных глубин Арифметика - великого магистра математики.

Первое уравнение требовало, чтобы "а" было умножено на "х", "b" на "у", а затем сложено вместе, чтобы равняться "с". Второе уравнение требовало, чтобы "d" было умножено на "х", "e" на "у", а затем вычтено и равнялось бы "f". Однако решить эту головоломку было нелегко, ибо уравнения были сложными и запутанными, а переменные "х" и "у" скрыты в туманной дымке математической тайны.

Только те, кто обладают силой ума и умением логически мыслить, смогут встретить вызов и отправиться в путешествие в мир математических загадок, чтобы найти решение этой тайны. Но будь осторожен, ибо неизвестные силы могут помешать твоему успеху и утащить тебя в бездну неразрешимых проблем.

И так, если ты готов сойти в темные глубины математической тайны и встретить вызов головоломки, то отправляйся в мир переменных "х" и "у", чтобы раскрыть эту тайну и открыть путь к свету знания. Но помни, что тайна системы уравнений лежит в тумане математической неопределенности, и только те, кто обладают силой воли и умением, смогут найти ответ.

Вход - строки содержащие коэффициенты a, b, c, d, e, f системы.

Выход - массивы numpy x и y - решения системы, каждый с новой строки

In [167]:
import numpy as np
a=np.array(input().split(), dtype=np.int32)
b=np.array(input().split(), dtype=np.int32)
c=np.array(input().split(), dtype=np.int32)
d=np.array(input().split(), dtype=np.int32)
e=np.array(input().split(), dtype=np.int32)
f=np.array(input().split(), dtype=np.int32)
x=c/a-b-y
#y=-f/d-e+x
print(x, y)

-7 -7 3 1 4 7 -8 -1 3 -4
-6 -7 -6 -4 2 10 9 -9 -3 11
0 9 6 10 -4 7 11 11 5 -7
-4 5 7 -2 -10 -11 1 -2 -1 -9
3 3 -5 11 3 -10 1 8 1 -10
-6 -5 8 -12 1 -1 -1 -10 9 11


NameError: ignored

Таким образом, задача заключается в том, чтобы написать функцию, которая принимает на вход два массива NumPy - один с напряжением и другой с сопротивлением, и возвращает массив с силой тока, рассчитанной по закону Ома.

In [168]:
import numpy as np
napr=np.array(input().split(), dtype=float)
sopr=np.array(input().split(), dtype=float)
i=napr/sopr
print(i)

15.39 13.98 5.63 24.61 8.45 9.8 19.04 20.34 1.31 22.83 22.61 15.49 10.33 19.05
22.55 8.73 1.05 12.42 3.89 12.69 17.6 12.98 7.74 19.52 23.97 9.65 8.35 18.98
[0.68248337 1.60137457 5.36190476 1.98148148 2.1722365  0.77226162
 1.08181818 1.56702619 0.16925065 1.16956967 0.94326241 1.60518135
 1.23712575 1.00368809]


На борту корабля были шесть контейнеров с ресурсами, помеченных метками a, b, c, d, e и f. Каждый контейнер содержал массивы numpy, представляющие различные ресурсы, которые были украдены. Вам нужно использовать эти массивы, чтобы рассчитать общую стоимость украденных ресурсов, используя следующее выражение:

(2a + 3b - 4c) * d ** 2 / (e - f)

Найдите общую стоимость украденных ресурсов, чтобы помочь нам восстановить нашу экономику и победить этих коварных космических пиратов!

Результат округляйте до одного знака после запятой.

In [179]:
from numpy import array
import numpy as np
a,b,c,d,e,f = [array(input().split(), float) for _ in range(6)]
rez=(2*a + 3*b - 4*c) * d ** 2 / (e - f)
rez_1=np.round(rez,1)
print(rez_1)

9 5 2 0 -9 -8 -1 -10 11 -11 7 -12
-9 8 -7 6 -9 -12 -4 -7 -7 0 4 6
-3 8 -8 -7 1 2 9 1 -8 -11 -2 6
-2 -9 -7 -10 -11 -7 1 2 9 2 -4 -9
2 -10 -9 -10 -9 -12 -1 -8 9 5 8 6
-7 6 6 9 2 4 4 -1 -6 -1 -11 -8
[   1.3  -10.1  -49.  -242.1  539.   183.8   10.    25.7  178.2   14.7
   28.6 -173.6]


Помогите этим отважным искателям найти потерянный город и вернуться домой живыми. Если все значения в массиве координат первого искателя больше, чем второго, то отправляемся в путь смело, возвращая True, иначе возвращаем False и оставляем их на волю судьбы."

Вход  в первой строке поступают через пробел значения x0, v, v0, a. Во второй строке значения времени - последовательность целых чисел, разделенных пробелом.

Вывод True или False  в соответствии с условием задачи.

In [183]:
import numpy as np
x0,v,v0,a=map(int,(input().split()))
t=np.array(input().split(), dtype=float)
x1 = x0 + v*t
x2=v0*t+(a*(t**2)/2)
#print(x1)
#print(x2)
if np.all(np.greater(x1,x2))==True:
  print('True')
else:
  print ('False')

100 5 -1 1
0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.1 5.6 6.1 6.6 7.1 7.6 8.1 8.6 9.1 9.6 10.1 10.6 11.1 11.6 12.1 12.6 13.1 13.6 14.1 14.6 15.2 15.7 16.2 16.7 17.2 17.7 18.2 18.7 19.2 19.7 20.2 20.7 21.2 21.7 22.2 22.7 23.2 23.7 24.2 24.7 25.3 25.8 26.3 26.8 27.3 27.8 28.3 28.8 29.3 29.8 30.3 30.8 31.3 31.8 32.3 32.8 33.3 33.8 34.3 34.8 35.4 35.9 36.4 36.9 37.4 37.9 38.4 38.9 39.4 39.9 40.4 40.9 41.4 41.9 42.4 42.9 43.4 43.9 44.4 44.9 45.5 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0
False


ИМТ = масса тела (в килограммах) / (рост (в метрах))^2.

Вход - четыре строки m1, h1, m2, h2 - действительных чисел разделенных пробелом, содержащих массы и высоты двух групп воинов.

Выход - True или False в соответсвии с условием задачи.

In [185]:
import numpy as np
m1,h1,m2,h2=(np.array(input().split(), float) for _ in range(4))
imt_1=m1/h1**2
imt_2=m2/h2**2
if np.any(np.greater(imt_1,imt_2))==True:
  print('True')
else:
  print ('False')

54.9 57.9 72.5 52.5 71.3 54.1 60.3 62.4 66.1 62.1 71.0 56.5 67.3 55.2
164.7 130.1 197.3 168.9 147.5 190.8 126.7 191.2 214.6 167.5 120.8 192.7 141.4 169.6
57.4 86.4 56.8 74.1 61.1 75.0 78.0 70.0 83.8 72.8 92.4 65.8 87.5 78.9
169.1 174.0 162.6 128.2 160.4 175.5 122.3 190.6 132.7 132.9 196.2 211.4 160.4 217.1
True


Ахои, матросы! У нас на корабле имеются два массива показателей - "Альфа" и "Браво". Необходимо вычислить логическое выражение, которое определяет, когда значение показателя "Альфа" больше, чем значение показателя "Браво", при условии, что значение "Альфа" не равно нулю. Пристегните ремни безопасности, мы отправляемся в плавание по массивам!

In [192]:
import numpy as np
arr1, arr2=(np.array(input().split(), int) for _ in range(2))
b=np.empty(0, dtype=np.int32)
for i in arr1:
  if i==0:
    b=np.append(b,np.nan)
  else:
    b=np.append(b,i)
a=np.greater(b,arr2)
print(a)

0 1 4 2 6 4
-3 2 5 2 1 5
[False False False False  True False]


После расчета, если хотя бы при одном значении объем газа больше порогового значения 0.1, таинственная граница раскроется перед нашей группой исследователей, позволяя им продолжить свое путешествие по неизведанным местам галактики. Однако, если объем газа окажется меньше порогового значения для всех значений, то наша группа исследователей останется в заточении, не имея возможности вернуться домой.

Для решения задачи необходимо использовать уравнение Менделеева-Клапейрона: PV = nRT

где P - давление газа, V - его объем, n - количество молей газа, R = 8.31 - универсальная газовая постоянная, T - абсолютная температура.

Даны массивы: pressure - давление газа, count - массив количества  вещества (в молях), temperature - температура газа, .

Вывод: True, False в соответствии с условиями задачи.

In [203]:
import numpy as np
P, n, T=(np.array(input().split(), float) for _ in range(3))
R=8.31
V=(n*R*T)/P
z=np.any(np.greater(V,0.1))
print(z)

92188 91305 103791 96000 100349 100408 104269 100041 92055 94519 101417 101299 96622 91425 99481 103185 100062 97698 103011 101050 90604 100031
1 3 1 2 1 1 1 1 4 2 2 1 1 4 1 1 1 4 4 2 2 3
332 265 310 279 377 306 287 315 291 283 357 274 320 350 271 265 252 313 285 357 253 330
True
