<a href="https://colab.research.google.com/github/Stanislaff-666/python_practice/blob/main/Numpy_%D0%9E%D0%B4%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a=np.arange(1,10.5,0.5)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [ ]:
import numpy as np
a=np.linspace(-5,5,10)
print(a)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [ ]:
import numpy as np
a=np.arange(10,0.5,-1)
print(a)

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [ ]:
import numpy as np
a=int(input('введите число'))
arr=np.random.rand(a)
print(arr)

введите число10
[0.09178413 0.34518624 0.66275252 0.44171349 0.55148779 0.70371249
 0.58940123 0.04993276 0.56179184 0.76635847]


На вход подаются 2 числа a и b в виде строки чисел через пробел. Создайте массив NumPy, содержащий числа от a до b включительно, кратные 3, выведите его на экран,

In [ ]:
import numpy as np
a, b = map(int, input().split())
arr = np.arange(a, b + 1, 1)
res = []
for i in arr:
  if i % 3 == 0:
    res.append(i)
print(np.array(res))

-5 15
[-3  0  3  6  9 12 15]
[-3, 0, 3, 6, 9, 12, 15]


На вход подается целое число n. Cоздайте массив из n случайных действительных чисел в интервале от 0 до 1 не включительно.

Важно: перед генерацией чисел используйте строчку np.random.seed(32).

In [ ]:
import numpy as np
a=int(input())
np.random.seed(32)
arr=np.random.rand(a)
print(arr)


10
[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696  0.81620514
 0.10108656 0.92848807 0.60910917 0.59655344]


На вход подается целое число n>=1. Создайте массив, содержащий n первых простых чисел. Выведите его на экран.

In [ ]:
import numpy as np
from sympy import prime
a=int(input())
res = []
nth_prime = prime(range(1,a))
res.append(a)
print(res)


3


ValueError: ignored

In [ ]:
# import sympy
from sympy import prime
n = 5
# Use prime() method
nth_prime = prime(n)
print("The {}th prime is {}".format(n, nth_prime))

The 5th prime is 11


На вход подается 2 действительных числа а>0, b>=0.001. Создайте массив, содержащий числа от -a до числа c <= a, такого что a - c <= b, с шагом b. Числа округляйте до двух знаков после запятой, используя np.round(). Выведите массив на экран.

In [ ]:
a,b=input().split()
x=float(a)
y=float(b)
arr=np.round(np.arange (-x, x + y/10, y),1)
print(arr)

10 .3
[-10.   -9.7  -9.4  -9.1  -8.8  -8.5  -8.2  -7.9  -7.6  -7.3  -7.   -6.7
  -6.4  -6.1  -5.8  -5.5  -5.2  -4.9  -4.6  -4.3  -4.   -3.7  -3.4  -3.1
  -2.8  -2.5  -2.2  -1.9  -1.6  -1.3  -1.   -0.7  -0.4  -0.1   0.2   0.5
   0.8   1.1   1.4   1.7   2.    2.3   2.6   2.9   3.2   3.5   3.8   4.1
   4.4   4.7   5.    5.3   5.6   5.9   6.2   6.5   6.8   7.1   7.4   7.7
   8.    8.3   8.6   8.9   9.2   9.5   9.8]


На вход подается целое число b > 0. Создайте массив numpy, содержащий b чисел от 0 до pi включительно. Для генерации числа пи используйте numpy константу np.pi. Выведите массив на экран.

In [ ]:
import numpy as np
a=int(input())
arr=np.linspace(0,np.pi,a)
print(arr)

10
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


На вход подается целое число n>1. Создайте numpy массив, содержащий n первых чисел Фибоначчи, выведите его на экран.

In [ ]:
n=int(input())
arr=np.arange(0,n,1)
print(arr)

3
[0 1 2]


In [ ]:
fib1 = fib2 = 1
n = int(input())
print(fib1, fib2, end=' ')

for i in range(2, n):
    fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')


5
1 1 2 3 5 

In [ ]:
import numpy as np
fNumber = int(input())
a = np.arange(0, fNumber)
length_a = len(a)

sqrt_five = np.sqrt(5)
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrt_five))
print(Fn)

5
[0. 1. 1. 2. 3.]


На вход подается целое число n>0, cоздайте одномерный массив numpy, состоящий из n элементов, равных числу pi, и выведите его на экран.

In [ ]:
import numpy as np
n = int(input())
print(np.full(n, np.pi))

2
[3.14159265 3.14159265]


На вход подается строка слов, разделенных пробелом, создайте одномерный массив numpy, содержащий эти слова. Выведите массив на экран.

In [ ]:
import numpy as np
a=input()
arr=np.array(a.split())
print(arr)

sd dns sdksl sj
['sd' 'dns' 'sdksl' 'sj']


На вход подается строка, создайте одномерный массив numpy, содержащий символы этой строки. Выведите массив на экран

In [ ]:
import numpy as np
a=input()
list_1=list(a)
arr=np.array(list_1)
print(arr)

аро длы фвфыв98 фы_о
['а' 'р' 'о' ' ' 'д' 'л' 'ы' ' ' 'ф' 'в' 'ф' 'ы' 'в' '9' '8' ' ' 'ф' 'ы'
 '_' 'о']


На вход подается строка состоящая из слов, разделенных пробелом. Создайте одномерный массив, содержащий длины этих слов. Выведите массив на экран.

In [ ]:
import numpy as np
q = input()
word=q.split()
word_lengths = [len(word) for word in words]
arr=np.array(word_lengths)
print(arr)

аро длы фвфыв98 фы_о
[3 3 7 4]


На вход поступают две строки, состоящие из чисел, разделённых пробелом.

Необходимо создать два массива numpy a и b, в которые поместить эти числа. При этом нужно правильно определить какой тип использовать, исходя из данных, содержащихся в строках.

Затем на основе данных второго массива b необходимо создать третий c, значения которого взяты из второго массива b, а тип данных равен типу данных первого массива a.

Полученные три массива a, b, c вывести на экран в порядке их создания через пробел.

In [ ]:
import numpy as np
data_1=list(input())
data_2=list(input())
qs=data_1.dtype
qx=type(data_2)
print(qs, qx)

1 2 3
2.2 2 2


AttributeError: ignored

In [ ]:
import numpy as np
data_1=input()
data_2=input()
arr1 = np.fromstring(data_1, dtype=None, sep=" ")
arr2 = np.fromstring(data_2, dtype=None, sep=" ")
print(arr1, arr2)

1 2 3
2.2 2 2
[1. 2. 3.] [2.2 2.  2. ]


In [ ]:
import numpy as np
s1=np.array(input().split())
s2=np.array(input().split())
a=s1.dtype
b=s2.dtype
print (a, b)

1 2 3
2.2 2 2
<U1 <U3


In [ ]:
import numpy as np
data_1=input().split()
data_2=input().split()
for i in data_1:
  if i%1==0:
    data_1.astype(int)
  else:
    data_1
print(type(data_1))

1 2 3
2.2 2 2


TypeError: ignored

Напишите функцию convert_type(), которая принимает на вход одномерный numpy массив и возвращает новый массив того же размера, но с типом данных str.

Нужно только определить функцию, вызывать ее не нужно!

In [ ]:
import numpy as np
arr=np.array(str(input()))
print(type(arr))
print(arr)

2 3.3 5 5
<class 'numpy.ndarray'>
2 3.3 5 5


На вход подается целое число n.

Напишите программу, которая создает одномерный массив из n чисел, равномерно распределенных в диапазоне от 0 до 100 (включительно), и выводит в первой строке сам массив и в следующей строке его размерность, форму и количество элементов через пробел.ndim, shape и size.

In [ ]:
import numpy as np
arr=np.linspace(0, 100, int(input()))
print (arr)
print(arr.ndim, arr.shape, arr.size)

10
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
1 (10,) 10


На вход подается  строка действительных чисел разделенных пробелом. Напишите программу, которая создает одномерный массив из чисел, введенной строки с типом float16. Выведите на экран данный массив его тип и размер в байтах каждого элемента массива.

In [ ]:
import numpy as np
a=input().split()
arr=np.array(a)
num16 = np.float16(arr)
print(num16)
print (num16.dtype, num16.itemsize)

3.4 6 4.333
[3.4   6.    4.332]
float16 2


In [ ]:
import numpy as np
arr_fl = np.array(input().split(), dtype = np.float16)
print(arr_fl)
print(arr_fl.dtype, arr_fl.itemsize)

3.4 6 4.333
[3.4   6.    4.332]
float16 2


На вход подается строка целых чисел, разделенных пробелом, в которой содержится количество проданных за день билетов в течение прошедшей недели.

Создайте массив NumPy из этих данных, используйте тип int64. Выведите на экран сам массив в первой строке, среднее количество проданных за неделю билетов, округленное до трех знаков после запятой, и  тип данных массива через пробел во второй строке.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int64)
print(arr)
print(round(sum(arr)/len(arr),3), arr.dtype)

100 200 300 150 250 175 225
[100 200 300 150 250 175 225]
200.0 int64


На вход поступает строка целых чисел, разделенных запятой с пробелом, в которой записана температура в городе N за каждый день месяца.

Создайте массив numpy из данных о температуре в городе за каждый день месяца. Выведите на экран максимальную температуру в городе за месяц, размерность массива, его форму и тип, в одной строке, через пробел.

In [ ]:
import numpy as np
arr=np.array(input().split(', '), dtype=np.int32)
print (max(arr), arr.ndim, arr.shape, arr.dtype)

10, 15, 20, 25, 20, 18, 16, 21, 23, 22, 19, 14, 12, 11, 13, 17, 18, 19, 20, 22, 25, 27, 24, 23, 20, 18, 16, 12, 10, 11
27 1 (30,) int32


На вход поступает строка целых чисел, в которой содержатся данных о загрязнении воздуха за некоторый период времени.

Создайте массив numpy из данных о загрязнении воздуха. Выведите на экран количество дней в году, когда уровень загрязнения воздуха превышал норму. Нормой считайте значение 45.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
result=0
for i in arr:
  if i>45:
    result+=1
print(result)

33 57 87 51 31 31 87 37 65 98 91 41 29 59 43 41 68 39 65 17 11 66 1 74 77 91 79 54 43 19 41 4 45 9 36 55 86 29 29 18 71 90 68 40 39 57 63 24 24 13 32 48 27 3 28 95 19 64 42 60 33 86 23 96 54 1 25 49 79 94 77 44 44 79 53 66 25
37


Лесной гном собирает золотые яблоки, которые растут на деревьях в его лесу. Он создает массив numpy из количества яблок, которые он нашел на каждом дереве. Выведите на экран суммарное количество яблок, найденных гномом. Определите тип данных массива.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
print(sum(arr), arr.dtype)

40 12 28 4 7 38 21 9 3 5 42 26 34 4 7 12 36 22 22 6 35 19 4 44 32 38 7 11 30 26 5 33 7
669 int32


Маленький рыцарь отправляется на поиски драконьего гнезда. Он создает массив numpy из количества драконов в каждом гнезде, которые он обнаруживает в своем путешествии. Выведите на экран наименьшее количество драконов в гнезде и индекс гнезда с максимальным количеством драконов. Если ему повстречалось несколько гнезд с максимальным количеством драконов, выведите индекс первого встретившегося ему гнезда.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
max=arr.max()
list_1=list(arr)
q=list_1.index(max)
print (min(arr), q)

18 44 10 9 7 31 18 21 40 41 42 6 16 39 41 5 14 26 2 32 34 17 20 26 14 36 12 3 6 12 44 17 10
2 1


Пираты обнаруживают сундук с сокровищами на необитаемом острове. Они создают массив numpy из веса каждой монеты в сундуке, округляя вес каждой монеты до трех знаков после запятой. Выведите на экран суммарный вес сокровищ, которые они обнаружили, и определите тип данных массива.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.float64)
print (sum(arr), arr.dtype)

164.357 248.462 337.148 1.408 661.915 376.46 452.997 364.914 366.963 50.349 104.352 17.029 373.695 386.679 313.316 67.886 659.198 191.347 39.324 300.299 367.913 172.754 564.768 455.142 572.764 517.435 329.967 435.285 567.868 228.024 243.25 567.91 226.866
10728.044 float64


Принцесса хранит свои волшебные заклинания в заколдованном замке. Она создает массив NumPy из слов заклинания. Выведите на экран количество слов заклинания с нечетным количеством символов и количество слов заклинания, в которых больше 5 символов. Определите тип данных массива.

Слово - последовательность символов, разделенная пробелами.

In [ ]:
import numpy as np
arr=np.array(input().split())
res=0
res1=0
for i in arr:
  if len(i)>5:
    res+=1
for x in arr:
  if len(x)%2!=0:
    res1+=1
print(res1, res, arr.dtype)

Ветер времени взлетит, чтобы привнести силы в мою сущность, и я стану непобедимой в любой битве
14 5 <U11


Главный историк Средиземья ведет записи о событиях, происходящих в мире. Он создает массив numpy из объектов datetime, представляющих даты ключевых событий в истории мира. Выведите на экран тип данных массива, даты самого раннего и самого позднего событий.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=object)
print(arr.dtype, arr.min(), arr.max())

1598-04-29 1711-11-28 1661-05-06 0869-11-22 0930-05-22 0987-05-06 0827-05-22 1029-11-04 1255-02-12 1123-11-13 1697-03-17 1384-01-21 1408-06-10 1166-09-04 1109-09-18
object 0827-05-22 1711-11-28


Детектив Джо Ривера получил информацию о местонахождении опасного преступника по кличке Кармен. Он создает массив numpy из булевых значений, где True означает наличие признаков, свидетельствующих о присутствии Кармен на заданной территории. Определите тип данных массива и выведите на экран количество локаций, в которых может находиться Кармен.

In [ ]:
import numpy as np
arr=np.array(input().split())
ai=np.array(input().split(), dtype=bool)
res=[]
result=0
for i in arr:
  if i=='True':
    res.append(1)
  else:
    res.append(0)
for i in res:
  if i==1:
    result+=1
print(result, ai.dtype)

True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True
True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True
23 bool


In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=str)
arr=np.array(arr1, dtype=bool)
res=[]
result=0
for i in arr:
  if i=='True':
    res.append(1)
  else:
    res.append(0)
for i in res:
  if i==1:
    result+=1
print(arr,result, arr.dtype)

True False  True  True  True  True  True  True False False  True  True True False False False  True  True  True  True  True False  True  True True  True False  True False  True False  True False False  True


ValueError: ignored

Шерлок Холмс попросил вас создать массив numpy, в котором содержится информация о телефонных звонках, совершенных потенциальными жертвами серийного убийцы. На вход поступает строка в которой значение 1 в массиве означает, что звонок был совершен в момент времени, когда было совершена убийство. Значение 0 - звонок был совершен в другое время или не был совершен вообще. Создайте массив numpy на основе этой строки, содержащий данные за последний месяц в виде булевых значений. Выведите на экран количество звонков, которые совершались в моменты времени, когда были совершены убийства и тип данных массива, через пробел.

In [ ]:
import numpy as np
arr=np.array(input().split(), dtype=np.int32)
sum=0
for i in arr:
  if i==1:
    sum+=1
print(sum)

1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0
0


In [ ]:
import numpy as np
a=list(input().split())
print (a)
arr=np.array(a,dtype=bool)
print(arr)

1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0
['1', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '0', '1', '1', '0', '0']
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


На вход поступают две строки, содержащие целые числа. Необходимо создать на их основе два массива numpy, объединить их, а затем повторить полученный массив три раза. Выведите на экран итоговый массив.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
arr3=np.concatenate((arr1,arr2))
arr3=np.repeat(arr3, 3)
print(arr3)

4 4 16 27 42 49 32 1 5 26 34 37 45 12 2 4 20 14 38 50
21 36 23 30 51 24 10 26 51 26 45 26 11 30 29 49 36 9 13 27
[ 4  4  4  4  4  4 16 16 16 27 27 27 42 42 42 49 49 49 32 32 32  1  1  1
  5  5  5 26 26 26 34 34 34 37 37 37 45 45 45 12 12 12  2  2  2  4  4  4
 20 20 20 14 14 14 38 38 38 50 50 50 21 21 21 36 36 36 23 23 23 30 30 30
 51 51 51 24 24 24 10 10 10 26 26 26 51 51 51 26 26 26 45 45 45 26 26 26
 11 11 11 30 30 30 29 29 29 49 49 49 36 36 36  9  9  9 13 13 13 27 27 27]


На вход поступают две строки. В первой строке содержится последовательность целых чисел, разделенных пробелом, во второй строке целое число i. Из первой строки нужно создать массив numpy и затем удалить из него с помощью функции delete() элемент с индексом i. Выведите на экран исходный и итоговый массивы, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input(), dtype=np.int32)
print (arr1)
arr1=np.delete(arr1, arr2)
print(arr1)

28 22 24 9 32 33 53 27 50 30 48 49
4
[28 22 24  9 32 33 53 27 50 30 48 49]
[28 22 24  9 33 53 27 50 30 48 49]


На вход поступают два числа a и b в одной строке, разделенные пробелом. Вам нужно создать массив numpy A чисел от a до b (b включительно, если оно нечетное), содержащий только нечетные числа. Затем создайте новый массив B путем повторения каждого элемента массива А дважды. Выведите на экран исходный A и итоговый массив B, каждый с новой строки.

In [ ]:
import numpy as np
a, b = map(int, input().split())
if b%2!=0:
  arr1=np.arange(a,b+1)
else:
  arr1=np.arange(a,b)
#print(arr1)
arr2=np.empty(0, dtype=int)
for i in arr1:
  if i%2!=0:
    arr2=np.append(arr2, i)
  else:
    arr2
print(arr2)
arr2=np.repeat(arr2,2)
print(arr2)

3 19
[ 3  5  7  9 11 13 15 17 19]
[ 3  3  5  5  7  7  9  9 11 11 13 13 15 15 17 17 19 19]


На вход поступают две строки, содержащие целые  числа, разделенные пробелом. На их основе создайте два одномерных масcива numpy a и b. Далее создайте третий массив c, который состоит из элементов массива a, затем из элементов массива b. Причем каждый элемент в массиве с повторяется 2 раза. Выведите на экран массивы a, b, c каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
arr3=np.concatenate((arr1,arr2)).repeat(2)
print(arr1)
print(arr2)
print(arr3)

19 34 39 -5 41 27 34 8
45 -5 12 6 48
[19 34 39 -5 41 27 34  8]
[45 -5 12  6 48]
[19 19 34 34 39 39 -5 -5 41 41 27 27 34 34  8  8 45 45 -5 -5 12 12  6  6
 48 48]


На вход поступает целое число n. Вам нужно создать массив a из n случайных действительных чисел равномерно распределенных в диапазоне от 0 до 1. Затем создайте массив b, увеличив размер массива a до 2n элементов с помощью функции resize(). Выведите на экран исходный массив a, итоговый массив b, каждый вывод с новой строки.

In [ ]:
import numpy as np
n = int(input())
np.random.seed(n)
arr1=np.random.rand(n)
arr2=np.resize(arr1, (2*n))
print(arr1, arr2, sep='\n')

10
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.77132064 0.02075195
 0.63364823 0.74880388 0.49850701 0.22479665 0.19806286 0.76053071
 0.16911084 0.08833981]


На вход поступает строка с целыми числами разделенными пробелами. На основе этой строки необходимо создать numpy массив а. Затем из массива а создайте массив b, в котором удалены все повторяющиеся элементы кроме первого. Порядок оставшихся элементов в массиве b должен совпадать с порядком этих элементов в массиве а. Выведите исходный массив а, итоговый b и тип элементов массива b, каждый вывод с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.empty(0, dtype=int)
for i in arr1:
  if i not in arr2:
    arr2=np.append(arr2, i)
  else:
    arr2
print(arr1)
print(arr2)
print(arr2.dtype)

4 5 2 3 5 3 5 2 3 2 3 5 4 5 2 4 3 3
[4 5 2 3 5 3 5 2 3 2 3 5 4 5 2 4 3 3]
[4 5 2 3]
int64


На вход поступают две строки. В первой содержатся целые числа, разделенные пробелом, во второй одно целое число n. На основе первой строки создать numpy массив a. Далее создать numpy массив b, в котором первым элементом является число n, далее следуют числа массива a. Массивы a и b вывести на экран, каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input(), dtype=np.int32)
arr3=np.empty(0, dtype=int)
arr3=np.insert(arr1, 0, arr2)
print(arr1)
print(arr3)

2 24 17 23 29 23 18 26
-1
[ 2 24 17 23 29 23 18 26]
[-1  2 24 17 23 29 23 18 26]


На вход поступают две строки. В первой идут целые числа разделенные пробелом, во второй единственное целое число n. На основе чисел первой строки создайте массив a. Затем на основе массива a создайте массив b, в котором будут числа массива а > n. Порядок чисел в массиве b должен совпадать с порядком в массиве a. При этом типы элементов в массиве a и b должны быть одинаковыми. Выведите на экран массивы a и b, каждый с новой строки.

In [ ]:
import numpy as np
a=np.array(input().split(), dtype=np.int32)
#arr2=np.array(input(), dtype=np.int32)
c=int(input())
b=np.empty(0, dtype=np.int32)
for i in a:
  if i>c:
    b=np.append(b, i)
  else:
    b
print(a, b, a.dtype==b.dtype, sep='\n')

5 0 9 20 14 18 28 26 18 3
9
[ 5  0  9 20 14 18 28 26 18  3]
[20 14 18 28 26 18]
True


На вход поступают две строки. В первой строке расположены целые числа, разделенные пробелом. Во второй строке два целых числа start и end. Создайте массив a на основе чисел первой строки. Затем на основе массива a создайте массив b, который состоит из всех элементов массива a, кроме тех которые находятся на позициях от  start до end+1 не включительно. Выведите на экран массивы a и b каждый с новой строки.

In [ ]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
a, b = map(int, input().split())
print(arr1)
arr2=np.delete(arr1, np.arange(a,b+1))
print(arr2)

15 21 12 3 27 20 20 27 0 4
3 6
[15 21 12  3 27 20 20 27  0  4]
[15 21 12 27  0  4]


В первой строке поступает целое число n - количество массивов целых чисел, разделенных пробелом, которые поступают на вход в следующих n строках. В последней строке поступает целое число m - максимальное количество элементов в итоговом массиве. Необходимо объединить все массивы и создать массив numpy, назвав его a. Если количество элементов в них больше m, обрезать его. При этом тип итогового массива должен быть int64. Затем вывести итоговый массив на экран.

In [ ]:
import numpy as np
n=int(input())
a=np.array(input().split(), dtype=np.int64)
m=int(input())
a = a[:m]
print(a)
print(a.dtype)

4
22 -8 50 7 27 13 5 3 11 1 10 4 27 20 27 1 10 4 27 20 2 5
10
[22 -8 50  7 27 13  5  3 11  1]
int64


На вход поступает массив элементов, разделенных пробелом в первой строке, необходимо на его основе создать numpy массив a. Во второй строке дается название типа, к которому необходимо привести элементы массива а. Наконец в третьей строке последовательность целых чисел - индексы элементов которые нужно удалить из массива а. Выведите итоговый массив на экран.

In [ ]:
import numpy as np
arr1=np.array(input().split())
t=input()
arr3=np.array(input().split(), dtype=np.int64)
#print(arr1)
qqq=arr1.astype(t)
#print(qqq)
zzz=np.delete(qqq, arr3)
print(zzz)

1 2 3 4 5 6 7
int32
1 3 4
[1 3 6 7]


На вход поступают три строки. В первой и второй строках - числа (действительные или целые), разделенные пробелом. Необходимо на их основе создать два numpy массива a и b. В третьей строке целое число n - размер итогового массива. Необходимо объединить массивы a и b, привести тип элементов получившегося массива к типу элементов первого массива а и привести размер получившегося массива к n. Вывести итоговый массив на экран.

In [ ]:
import numpy as np
s1=input().split()
s2=input().split()
n=int(input())
if '.' in s1[1]:
    arr1=np.array(s1,dtype=np.float64)
else:
    arr1=np.array(s1,dtype=np.int32)
if '.' in s2[1]:
    arr2=np.array(s2,dtype=np.float64)
else:
    arr2=np.array(s2,dtype=np.int32)
tp=arr1.dtype
qq=arr2.astype(tp)
arr3=np.concatenate((arr1,qq))
resized_arr=np.resize(arr3, (n,))
print(resized_arr)




12 3 1 8 9 3 5 3 11 0 11 11 7 8
5.814 18.797 21.87 6.032 3.065 3.861 9.439 11.137 3.36 16.504
18
[12  3  1  8  9  3  5  3 11  0 11 11  7  8  5 18 21  6]


Три мушкетера - Атос, Портос и Арамис - решили объединить свои одномерные массивы numpy целых чисел в один массив. Однако у каждого мушкетера есть свой массив разного размера. Помогите им объединить свои массивы в один массив, используя функцию concatenate.

In [ ]:
import numpy as np
s1=np.array(input().split(), dtype=np.float16)
s2=np.array(input().split(), dtype=np.float16)
s3=np.array(input().split(), dtype=np.float16)
arr1=np.concatenate((s1,s2, s3))
print(arr1)


12 3 1 8 9 3 5 3 11
22 -8 50 7 27
8 9 3 5 4 5 6
[12.  3.  1.  8.  9.  3.  5.  3. 11. 22. -8. 50.  7. 27.  8.  9.  3.  5.
  4.  5.  6.]


В первой строке поступает целое число n - количество массивов с числами, разделенными пробелами. Во второй строке - название типа к которому нужно привести элементы всех массивов, далее в следующих n строках идут сами массивы.  В последней строке идет целое число m - количество элементов, которое должно быть в каждом из массивов. Привести тип элементов всех массивов к необходимому типу, также привести размерность каждого массива к типу n, если при этом размерность нового массива больше, чем исходного, лишние значения заполнить нулями. Вывести все получившиеся массивы на экран через пробел.

In [ ]:
import numpy as np
cnt=int(input().split())
form=input().split()
arr=np.array(input().split())
count_el=input().split()


В древнем доме на окраине города, где жил исследователь мистических артефактов, был обнаружен таинственный массив. Символы на массиве были написаны на древнем языке, и никто не мог прочитать их. Однако массив был наделен темной магией, и когда исследователь начал изучать его, массив начал расширяться и превращаться в портал в иной мир. Помогите исследователю уменьшить размеры массива, используя функцию resize, чтобы остановить его расширение и предотвратить открытие портала в темный мир. Однако, будьте осторожны, вам придется преодолеть множество трудностей и противостоять неизвестным силам, чтобы остановить этот зловещий массив.

In [ ]:
import numpy as np
arr=np.array(input().split())
#arr1=np.resize(arr, 5)
#print(arr1)
arr.resize(5)
print(arr)

4 3 2 12 11 1 4 3 7 11 1 10 2 10 3 8 6 7 7 7 7 6 5 4 7 0 7 5 0 6 9 4 5 5 0 3 12 1 9 1 2 3 8 5 5
['4' '3' '2' '12' '11']


На вход поступает строка целых чисел, разделенных пробелом. Создайте на ее основе numpy массив а. Затем  создайте новый массив b, содержащий только первые 5 элементов исходного массива. Оба массива выведите на экран, каждый с новой строки.

In [2]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[:5])
print(arr1)
print(arr2)

30 3 12 8 9 10 3 3 14 16
[30  3 12  8  9 10  3  3 14 16]
[30  3 12  8  9]


На вход поступает последовательность действительных чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий только последние 3 элемента исходного массива. Оба массива вывести на экран, каждый с новой строки.

In [14]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float32)
arr2=np.array(arr1[::-1])
q=arr2[:3]
r=q[::-1]
print(arr1)
print(r)

24 24 15 2 19 4 30 16 32 30
[24. 24. 15.  2. 19.  4. 30. 16. 32. 30.]
[16. 32. 30.]


In [21]:
import numpy as np
arr1=np.array(input().split(), dtype=np.float32)
arr2=np.array(arr1[-3:])
print(arr1)
print(arr2)

24 24 15 2 19 4 30 16 32 30
[24. 24. 15.  2. 19.  4. 30. 16. 32. 30.]
[16. 32. 30.]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий все элементы исходного массива в обратном порядке. Оба массива вывести на экран, каждый с новой строки

In [22]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[::-1])
print(arr1)
print(arr2)

24 24 15 2 19 4 30 16 32 30
[24 24 15  2 19  4 30 16 32 30]
[30 32 16 30  4 19  2 15 24 24]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий только элементы исходного массива с нечетными индексами. Оба массива вывести на экран, каждый с новой строки.

In [23]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[1::2])
print(arr1)
print(arr2)

20 8 3 25 16 9 16 20 2 10
[20  8  3 25 16  9 16 20  2 10]
[ 8 25  9 20 10]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий элементы исходного массива, кроме первых 3 и последних 2. Оба массива вывести на экран, каждый с новой строки.

In [24]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[3:-2])
print(arr1)
print(arr2)

3 27 1 11 0 26 23 16 21 11 5
[ 3 27  1 11  0 26 23 16 21 11  5]
[11  0 26 23 16 21]


На вход поступает строка целых чисел, разделенных пробелом. На ее основе создать одномерный numpy массив чисел a. Затем создать новый массив b, содержащий все элементы исходного массива, с индексами кратными 3. Оба массива вывести на экран, каждый с новой строки.

In [31]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(arr1[::3])
print(arr1)
print(arr2)
#b = np.array([a[i] for i in range(len(a)) if i % 3 == 0])

17 0 10 17 23 8 28 16 14 7 31 7 17 21 22 5 31 31 8 6 16 20 26 23 31
[17  0 10 17 23  8 28 16 14  7 31  7 17 21 22  5 31 31  8  6 16 20 26 23
 31]
[17 17 28  7 17  5  8 20 31]


На вход поступает две строки, содержащие одинаковое количество целых чисел, разделенных пробелом. На их основе создать список numpy, состоящий из элементов, которые находятся на четных позициях первого списка, затем следуют элементы, стоящие на нечетных позициях второго списка. Если длина списков нечетная, то последний элемент не учитывается. Полученный список вывести на экран.

In [49]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
if len(arr1)%2!=0 and len(arr2)%2!=0:
  g=arr1[:-1]
  b=arr2[:-1]
else:
  g=arr1
  b=arr2
arr1_1=np.array(g[::2])
arr2_2=np.array(b[1::2])
arr_rez=np.concatenate((arr1_1,arr2_2))
print(arr_rez)


27 22 24 1 26 20 6 14 31 7 31
83 92 1 49 43 45 78 6 27 33 27
[27 24 26  6 31 92 49 45  6 33]


Золушка готовится к балу, но у нее нет подходящих туфель. Ей нужно найти туфли, которые подойдут по размеру, а размер у нее это целое число, которое поступает на вход в первой строке. Во второй строке поступает массив, в котором каждый элемент - это размер туфель. Найдите все туфли, которые подходят Золушке. В качестве ответа выведите numpy массив из индексов туфель, которые подходят Золушке.

In [68]:
import numpy as np
arr1=np.array(input().split(), dtype=np.int32)
arr2=np.array(input().split(), dtype=np.int32)
result = np.where(arr2 == arr1)
print(result[0])

33
37 37 40 36 36 41 36 42 40 36 39 36 41 36 41 34 33 35 41 37 35
[16]


Вы исследуете древний храм, где вам нужно разгадать загадку, чтобы достать древний артефакт. Загадка представляет собой одномерный массив, который нужно перевернуть задом наперед, чтобы получить правильный ответ. Вы можете использовать срезы одномерных массивов numpy, чтобы перевернуть массив и раскрыть тайну.

In [78]:
import numpy as np
sl=list(input())
sl.reverse()
arr=np.array(sl)
print(arr)

имактеверксордеввлапуток
['к' 'о' 'т' 'у' 'п' 'а' 'л' 'в' 'в' 'е' 'д' 'р' 'о' 'с' 'к' 'р' 'е' 'в'
 'е' 'т' 'к' 'а' 'м' 'и']


Волшебная рыбка просит вас помочь ей отсортировать массив чисел. Она хочет, чтобы вы взяли первые 5 элементов массива и отсортировали их по убыванию. Затем вы должны взять последние 3 элемента массива и отсортировать их по возрастанию. Затем выведите получившийся массив в виде чисел, разделенных пробелом, на экран. Если вы выполните ее просьбу, она исполнит любое ваше желание.

In [111]:
import numpy as np
a = np.array(input().split(), dtype=np.int32)
b = sorted(a[:5], reverse=True)
c = sorted(a[-3:])
d = np.concatenate((b, c))
print(*d)

37 41 37 37 41 38 33 37 38 41 3
41 41 37 37 37 3 38 41


In [108]:
import numpy as np
sl=np.array(input().split(), dtype=np.int32)
sl_left=sl[:5]
sl_right=sl[-3:]
q=-np.sort(-sl_left)
a=np.sort(sl_right)
rez=np.concatenate((q,a))
rezz=' '.join(map(str, rez))
print(rezz)

37 41 37 37 41 38 33 37 38 41 3
41 41 37 37 37 3 38 41


Колдунья дала вам массив чисел и просит вас изменить его содержимое. Она хочет, чтобы вы взяли каждый второй элемент массива, начиная со второго, и заменили их на 0. Затем она хочет, чтобы вы взяли последние 3 элемента массива и заменили их на 1. Отдайте ей итоговый массив.

In [124]:
import numpy as np
arr=np.array(input().split(), dtype=np.int64)
b=np.empty(0, dtype=np.int64)
for i in arr:
  if arr[i]%2!=0:
    b=np.append(b,0)
  else:
    b=np.append(b,i)
print (b)

37 39 37 41 37 37 41 38 33 37 38 41 34 41 40 39 36 34 37 34 39 33 39 35 42 42 36


IndexError: ignored