<a href="https://colab.research.google.com/github/Stanislaff-666/python_practice/blob/main/Numpy_%D0%9E%D0%B4%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a=np.arange(1,10.5,0.5)
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [ ]:
import numpy as np
a=np.linspace(-5,5,10)
print(a)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [ ]:
import numpy as np
a=np.arange(10,0.5,-1)
print(a)

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [ ]:
import numpy as np
a=int(input('введите число'))
arr=np.random.rand(a)
print(arr)

введите число10
[0.09178413 0.34518624 0.66275252 0.44171349 0.55148779 0.70371249
 0.58940123 0.04993276 0.56179184 0.76635847]


На вход подаются 2 числа a и b в виде строки чисел через пробел. Создайте массив NumPy, содержащий числа от a до b включительно, кратные 3, выведите его на экран,

In [ ]:
import numpy as np
a, b = map(int, input().split())
arr = np.arange(a, b + 1, 1)
res = []
for i in arr:
  if i % 3 == 0:
    res.append(i)
print(np.array(res))

-5 15
[-3  0  3  6  9 12 15]
[-3, 0, 3, 6, 9, 12, 15]


На вход подается целое число n. Cоздайте массив из n случайных действительных чисел в интервале от 0 до 1 не включительно.

Важно: перед генерацией чисел используйте строчку np.random.seed(32).

In [ ]:
import numpy as np
a=int(input())
np.random.seed(32)
arr=np.random.rand(a)
print(arr)


10
[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696  0.81620514
 0.10108656 0.92848807 0.60910917 0.59655344]


На вход подается целое число n>=1. Создайте массив, содержащий n первых простых чисел. Выведите его на экран.

In [ ]:
import numpy as np
from sympy import prime
a=int(input())
res = []
nth_prime = prime(range(1,a))
res.append(a)
print(res)


3


ValueError: ignored

In [ ]:
# import sympy
from sympy import prime
n = 5
# Use prime() method
nth_prime = prime(n)
print("The {}th prime is {}".format(n, nth_prime))

The 5th prime is 11


На вход подается 2 действительных числа а>0, b>=0.001. Создайте массив, содержащий числа от -a до числа c <= a, такого что a - c <= b, с шагом b. Числа округляйте до двух знаков после запятой, используя np.round(). Выведите массив на экран.

In [ ]:
a,b=input().split()
x=float(a)
y=float(b)
arr=np.round(np.arange (-x, x + y/10, y),1)
print(arr)

10 .3
[-10.   -9.7  -9.4  -9.1  -8.8  -8.5  -8.2  -7.9  -7.6  -7.3  -7.   -6.7
  -6.4  -6.1  -5.8  -5.5  -5.2  -4.9  -4.6  -4.3  -4.   -3.7  -3.4  -3.1
  -2.8  -2.5  -2.2  -1.9  -1.6  -1.3  -1.   -0.7  -0.4  -0.1   0.2   0.5
   0.8   1.1   1.4   1.7   2.    2.3   2.6   2.9   3.2   3.5   3.8   4.1
   4.4   4.7   5.    5.3   5.6   5.9   6.2   6.5   6.8   7.1   7.4   7.7
   8.    8.3   8.6   8.9   9.2   9.5   9.8]


На вход подается целое число b > 0. Создайте массив numpy, содержащий b чисел от 0 до pi включительно. Для генерации числа пи используйте numpy константу np.pi. Выведите массив на экран.

In [ ]:
import numpy as np
a=int(input())
arr=np.linspace(0,np.pi,a)
print(arr)

10
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


На вход подается целое число n>1. Создайте numpy массив, содержащий n первых чисел Фибоначчи, выведите его на экран.

In [ ]:
n=int(input())
arr=np.arange(0,n,1)
print(arr)

3
[0 1 2]


In [ ]:
fib1 = fib2 = 1
n = int(input())
print(fib1, fib2, end=' ')

for i in range(2, n):
    fib1, fib2 = fib2, fib1 + fib2
    print(fib2, end=' ')


5
1 1 2 3 5 

In [ ]:
import numpy as np
fNumber = int(input())
a = np.arange(0, fNumber)
length_a = len(a)

sqrt_five = np.sqrt(5)
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrt_five))
print(Fn)

5
[0. 1. 1. 2. 3.]


На вход подается целое число n>0, cоздайте одномерный массив numpy, состоящий из n элементов, равных числу pi, и выведите его на экран.

In [224]:
import numpy as np
n = int(input())
print(np.full(n, np.pi))

2
[3.14159265 3.14159265]


На вход подается строка слов, разделенных пробелом, создайте одномерный массив numpy, содержащий эти слова. Выведите массив на экран.

In [235]:
import numpy as np
a=input()
arr=np.array(a.split())
print(arr)

sd dns sdksl sj
['sd' 'dns' 'sdksl' 'sj']


На вход подается строка, создайте одномерный массив numpy, содержащий символы этой строки. Выведите массив на экран

In [266]:
import numpy as np
a=input()
list_1=list(a)
arr=np.array(list_1)
print(arr)

аро длы фвфыв98 фы_о
['а' 'р' 'о' ' ' 'д' 'л' 'ы' ' ' 'ф' 'в' 'ф' 'ы' 'в' '9' '8' ' ' 'ф' 'ы'
 '_' 'о']


На вход подается строка состоящая из слов, разделенных пробелом. Создайте одномерный массив, содержащий длины этих слов. Выведите массив на экран.

In [267]:
import numpy as np
q = input()
word=q.split()
word_lengths = [len(word) for word in words]
arr=np.array(word_lengths)
print(arr)

аро длы фвфыв98 фы_о
[3 3 7 4]
